//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x263e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x153d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497fa
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int16_t *)(v5 + 0x39f0) = (int16_t)a1;
    *(int16_t *)(v5 + 0x39f2) = (int16_t)a2;
    *(int32_t *)(v5 + 0x39f4) = a3;
    *(char *)(v5 + 0x39f8) = (char)a4;
    *(int16_t *)(v5 + 0x39fa) = (int16_t)a5;
    *(int32_t *)(v5 + 0x39fc) = a6;
    *(int16_t *)(v5 + 0x3a00) = (int16_t)a7;
    *(char *)(v5 + 0x3a02) = (char)a8;
    *(char *)(v5 + 0x3e70) = (char)a9;
    *(char *)(v5 + 0x3a03) = (char)a10;
    *(int32_t *)(v5 + 0x3a04) = a11;
    *(int16_t *)(v5 + 0x3a08) = (int16_t)a12;
    *(int32_t *)(v5 + 0x3a0c) = a13;
    *(char *)(v5 + 0x3e71) = (char)a14;
    *(int16_t *)(v5 + 0x3a10) = (int16_t)a15;
    *(int16_t *)(v5 + 0x3a12) = (int16_t)a16;
    *(int32_t *)(v5 + 0x3a14) = a17;
    *(int32_t *)(v5 + 0x3a18) = a18;
    *(int32_t *)(v5 + 0x3a1c) = a19;
    *(int32_t *)(v5 + 0x3a20) = a20;
    *(int16_t *)(v5 + 0x3e72) = (int16_t)a21;
    *(int32_t *)(v5 + 0x3a24) = a22;
    *(int16_t *)(v5 + 0x3a28) = (int16_t)a23;
    *(int16_t *)(v5 + 0x3a2a) = (int16_t)a24;
    *(int32_t *)(v5 + 0x3a2c) = a25;
    return 0;
}

// Address range: 0x80497fa - 0x804a6a3
int32_t func_1(void) {
    // 0x804a567
    int32_t v1; // 0x80497fa
    __x86_get_pc_thunk_ax(v1);
    set_var(0, -0x33b6, -0x33b6, -1, 0, -1, 0xffe7, 1, 58, 58, 0, 1, 1, 0, 0xffff, 1, -9, 0, 0x71b24f34, 1, 0, 5, 0xfff6, -1, -0x5a854417);
    return 5;
}

// Address range: 0x804a6a3 - 0x804aa1f
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a6cc
    int32_t v3; // 0x804a6a3
    if (v1 == (char **)2) {
        // 0x804a6ce
        int32_t v4; // 0x804a6a3
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a6d4
        v2 = strcmp((char *)str, (char *)(v3 + 1102)) == 0;
    }
    // 0x804a6f4
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x296a), v3 + 1104, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x296c), v3 + 1108, v2);
    transparent_crc(*(int32_t *)(v3 + 0x296e), v3 + 1113, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2972), v3 + 1118, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2974), v3 + 1123, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2976), v3 + 1128, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x297a), v3 + 1133, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x297c), v3 + 1138, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2dea), v3 + 1143, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x297d), v3 + 1148, v2);
    transparent_crc(*(int32_t *)(v3 + 0x297e), v3 + 1153, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2982), v3 + 1158, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2986), v3 + 1163, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2deb), v3 + 1169, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x298a), v3 + 1175, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x298c), v3 + 1181, v2);
    transparent_crc(*(int32_t *)(v3 + 0x298e), v3 + 1187, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2992), v3 + 1193, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2996), v3 + 1199, v2);
    transparent_crc(*(int32_t *)(v3 + 0x299a), v3 + 1205, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2dec), v3 + 1211, v2);
    transparent_crc(*(int32_t *)(v3 + 0x299e), v3 + 1217, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x29a2), v3 + 1223, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x29a4), v3 + 1229, v2);
    transparent_crc(*(int32_t *)(v3 + 0x29a6), v3 + 1235, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2966), v2);
    return 0;
}

// Address range: 0x804aa1f - 0x804aa23
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804aa1f
    return result;
}

// Address range: 0x804aa23 - 0x804aa27
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804aa23
    int32_t result; // 0x804aa23
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
