//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x267e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c4a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bd9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x157d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804982f
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x39f0) = a1;
    *(int16_t *)(v5 + 0x39f4) = (int16_t)a2;
    *(int32_t *)(v5 + 0x39f8) = a3;
    *(char *)(v5 + 0x39fc) = (char)a4;
    *(char *)(v5 + 0x39fd) = (char)a5;
    *(int32_t *)(v5 + 0x3a00) = a6;
    *(char *)(v5 + 0x3a04) = (char)a7;
    *(int32_t *)(v5 + 0x3a08) = a8;
    *(char *)(v5 + 0x3a0c) = (char)a9;
    *(int16_t *)(v5 + 0x3a0e) = (int16_t)a10;
    *(int32_t *)(v5 + 0x3a10) = a11;
    *(int32_t *)(v5 + 0x3a14) = a12;
    *(int32_t *)(v5 + 0x3a18) = a13;
    *(char *)(v5 + 0x3a1c) = (char)a14;
    *(int32_t *)(v5 + 0x3a20) = a15;
    *(int32_t *)(v5 + 0x3a24) = a16;
    *(int32_t *)(v5 + 0x3a28) = a17;
    *(char *)(v5 + 0x3a2c) = (char)a18;
    *(int32_t *)(v5 + 0x3a30) = a19;
    *(int32_t *)(v5 + 0x3a34) = a20;
    *(int16_t *)(v5 + 0x3a38) = (int16_t)a21;
    *(char *)(v5 + 0x3a3a) = (char)a22;
    *(int32_t *)(v5 + 0x3a3c) = a23;
    *(int16_t *)(v5 + 0x3a40) = (int16_t)a24;
    *(int16_t *)(v5 + 0x3a42) = (int16_t)a25;
    *(int16_t *)(v5 + 0x3a44) = (int16_t)a26;
    *(int32_t *)(v5 + 0x3a48) = a27;
    *(int32_t *)(v5 + 0x3a4c) = a28;
    *(int16_t *)(v5 + 0x3a50) = (int16_t)a29;
    *(int32_t *)(v5 + 0x3a54) = a30;
    *(int16_t *)(v5 + 0x3a58) = (int16_t)a31;
    return 0;
}

// Address range: 0x804982f - 0x804a60f
int32_t func_1(void) {
    // 0x804982f
    int32_t v1; // 0x804982f
    __x86_get_pc_thunk_ax(v1);
    set_var(-1, 1, -0x3fcb, 0, 1, 5, 0, 0x16851cc2, 94, 0x30fc, -2, 7, 0x348a9cfe, -40, -0x376f7dce, -0x3677dea4, 0x56c3, 176, -1, 0x7be154aa, -0x6466, 78, -8, 1, -0x3792, -0x1d30, 0xcdc273, -9, 0xb55e, -0x2d3cb75d, 1);
    return 33;
}

// Address range: 0x804a60f - 0x804aa5a
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a638
    int32_t v3; // 0x804a60f
    if (v1 == (char **)2) {
        // 0x804a63a
        int32_t v4; // 0x804a60f
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a640
        v2 = strcmp((char *)str, (char *)(v3 + 1318)) == 0;
    }
    // 0x804a660
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x29fe), v3 + 1320, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a02), v3 + 1324, v2);
    transparent_crc(-0x4e4aad41, v3 + 1329, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a06), v3 + 1334, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a0a), v3 + 1339, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a0b), v3 + 1344, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a0e), v3 + 1349, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a12), v3 + 1354, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a16), v3 + 1359, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a1a), v3 + 1364, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a1c), v3 + 1369, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a1e), v3 + 1374, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a22), v3 + 1379, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a26), v3 + 1385, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a2a), v3 + 1391, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a2e), v3 + 1397, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a32), v3 + 1403, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a36), v3 + 1409, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a3a), v3 + 1415, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a3e), v3 + 1421, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a42), v3 + 1427, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a46), v3 + 1433, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a48), v3 + 1439, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a4a), v3 + 1445, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a4e), v3 + 1451, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a50), v3 + 1457, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a52), v3 + 1463, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a56), v3 + 1469, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a5a), v3 + 1475, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a5e), v3 + 1481, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a62), v3 + 1487, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2a66), v3 + 1493, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x29fa), v2);
    return 0;
}

// Address range: 0x804aa5a - 0x804aa5e
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804aa5a
    return result;
}

// Address range: 0x804aa5e - 0x804aa62
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804aa5e
    int32_t result; // 0x804aa5e
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
