//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x2d0e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x1c0d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497de
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(char *)(v5 + 0x49f0) = (char)a1;
    *(char *)(v5 + 0x49f1) = (char)a2;
    *(int16_t *)(v5 + 0x49f2) = (int16_t)a3;
    *(int32_t *)(v5 + 0x49f4) = a4;
    *(int32_t *)(v5 + 0x49f8) = a5;
    *(int16_t *)(v5 + 0x49fc) = (int16_t)a6;
    *(int32_t *)(v5 + 0x4a00) = a7;
    *(int16_t *)(v5 + 0x4a04) = (int16_t)a8;
    *(int16_t *)(v5 + 0x4a06) = (int16_t)a9;
    *(int32_t *)(v5 + 0x4a08) = a10;
    *(int32_t *)(v5 + 0x4a0c) = a11;
    *(int32_t *)(v5 + 0x4a10) = a12;
    *(int32_t *)(v5 + 0x4a14) = a13;
    *(int32_t *)(v5 + 0x4a18) = a14;
    *(int32_t *)(v5 + 0x4a1c) = a15;
    *(int32_t *)(v5 + 0x4a20) = a16;
    *(int16_t *)(v5 + 0x4e70) = (int16_t)a17;
    *(int32_t *)(v5 + 0x4e74) = a18;
    *(int32_t *)(v5 + 0x4a24) = a19;
    *(int32_t *)(v5 + 0x4a28) = a20;
    *(char *)(v5 + 0x4a2c) = (char)a21;
    *(int32_t *)(v5 + 0x4a30) = a22;
    *(int32_t *)(v5 + 0x4a34) = a23;
    *(int16_t *)(v5 + 0x4e78) = (int16_t)a24;
    *(int32_t *)(v5 + 0x4a38) = a25;
    *(char *)(v5 + 0x4a3c) = (char)a26;
    *(char *)(v5 + 0x4a3d) = (char)a27;
    *(int16_t *)(v5 + 0x4a3e) = (int16_t)a28;
    return 0;
}

// Address range: 0x80497de - 0x804ad21
int32_t func_1(void) {
    // 0x804ac41
    int32_t v1; // 0x80497de
    __x86_get_pc_thunk_ax(v1);
    set_var(-3, 81, 0, -2, -0x1e6073af, -0x6cd7, 15, 2980, -8, 0x46bac6, 8, 5, -5, -2, -1, -0x464fc0fa, 0, 0, -2, -0x3d86b6c9, 255, 0x57fb1e3a, -1, 0, -0x11094e2c, 165, 122, 1);
    return 0;
}

// Address range: 0x804ad21 - 0x804b0f1
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804ad4a
    int32_t v3; // 0x804ad21
    if (v1 == (char **)2) {
        // 0x804ad4c
        int32_t v4; // 0x804ad21
        int32_t str = *(int32_t *)(v4 + 4); // 0x804ad52
        v2 = strcmp((char *)str, (char *)(v3 + 1184)) == 0;
    }
    // 0x804ad72
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(char *)(v3 + 0x32ec), v3 + 1186, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x32ed), v3 + 1190, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x32ee), v3 + 1194, v2);
    transparent_crc(*(int32_t *)(v3 + 0x32f0), v3 + 1199, v2);
    transparent_crc(*(int32_t *)(v3 + 0x32f4), v3 + 1204, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x32f8), v3 + 1209, v2);
    transparent_crc(*(int32_t *)(v3 + 0x32fc), v3 + 1214, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3300), v3 + 1219, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3302), v3 + 1224, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3304), v3 + 1229, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3308), v3 + 1234, v2);
    transparent_crc(*(int32_t *)(v3 + 0x330c), v3 + 1239, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3310), v3 + 1244, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3314), v3 + 1249, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3318), v3 + 1254, v2);
    transparent_crc(*(int32_t *)(v3 + 0x331c), v3 + 1259, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x376c), v3 + 1265, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3770), v3 + 1271, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3320), v3 + 1277, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3324), v3 + 1283, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3328), v3 + 1289, v2);
    transparent_crc(*(int32_t *)(v3 + 0x332c), v3 + 1295, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3330), v3 + 1301, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3774), v3 + 1307, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3334), v3 + 1313, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3338), v3 + 1319, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3339), v3 + 1325, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x333a), v3 + 1331, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x32e8), v2);
    return 0;
}

// Address range: 0x804b0f1 - 0x804b0f5
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804b0f1
    return result;
}

// Address range: 0x804b0f5 - 0x804b0f9
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804b0f5
    int32_t result; // 0x804b0f5
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
