//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x1d7e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 3197));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804979b
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(char *)(v5 + 0x39f0) = (char)a1;
    *(int16_t *)(v5 + 0x39f2) = (int16_t)a2;
    *(int32_t *)(v5 + 0x39f4) = a3;
    *(char *)(v5 + 0x39f8) = (char)a4;
    *(int32_t *)(v5 + 0x39fc) = a5;
    *(char *)(v5 + 0x3a00) = (char)a6;
    *(char *)(v5 + 0x3a01) = (char)a7;
    *(int32_t *)(v5 + 0x3a04) = a8;
    *(char *)(v5 + 0x3a08) = (char)a9;
    *(int32_t *)(v5 + 0x3a0c) = a10;
    *(int32_t *)(v5 + 0x3a10) = a11;
    *(char *)(v5 + 0x3a14) = (char)a12;
    *(int32_t *)(v5 + 0x3a18) = a13;
    *(char *)(v5 + 0x3a1c) = (char)a14;
    *(char *)(v5 + 0x3a1d) = (char)a15;
    *(int16_t *)(v5 + 0x3a1e) = (int16_t)a16;
    *(int32_t *)(v5 + 0x3e70) = a17;
    *(int32_t *)(v5 + 0x3a20) = a18;
    *(int32_t *)(v5 + 0x3a24) = a19;
    *(int32_t *)(v5 + 0x3a28) = a20;
    *(int32_t *)(v5 + 0x3a2c) = a21;
    *(int32_t *)(v5 + 0x3a30) = a22;
    *(int16_t *)(v5 + 0x3a34) = (int16_t)a23;
    return 0;
}

// Address range: 0x804979b - 0x8049e1e
int32_t func_1(void) {
    // 0x804979b
    int32_t v1; // 0x804979b
    __x86_get_pc_thunk_ax(v1);
    set_var(8, 3494, -0x31270911, -120, -5, 1, -109, 93, 136, 0x5e415b52, -10, -6, 0x2f02481c, 1, -1, 2, 0, 1, 0x11e098a5, 0x5c23366, -0x72b2ade2, -0x7654de48, 0xffff);
    return 3494;
}

// Address range: 0x8049e1e - 0x804a15c
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049e47
    int32_t v3; // 0x8049e1e
    if (v1 == (char **)2) {
        // 0x8049e49
        int32_t v4; // 0x8049e1e
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049e4f
        v2 = strcmp((char *)str, (char *)(v3 + 1043)) == 0;
    }
    // 0x8049e6f
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(char *)(v3 + 0x31ef), v3 + 1045, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31f1), v3 + 1049, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31f3), v3 + 1053, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31f7), v3 + 1057, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31fb), v3 + 1061, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31ff), v3 + 1066, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3200), v3 + 1071, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3203), v3 + 1076, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3207), v3 + 1081, v2);
    transparent_crc(*(int32_t *)(v3 + 0x320b), v3 + 1086, v2);
    transparent_crc(*(int32_t *)(v3 + 0x320f), v3 + 1091, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3213), v3 + 1096, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3217), v3 + 1101, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x321b), v3 + 1106, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x321c), v3 + 1112, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x321d), v3 + 1118, v2);
    transparent_crc(*(int32_t *)(v3 + 0x366f), v3 + 1124, v2);
    transparent_crc(*(int32_t *)(v3 + 0x321f), v3 + 1130, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3223), v3 + 1136, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3227), v3 + 1142, v2);
    transparent_crc(*(int32_t *)(v3 + 0x322b), v3 + 1148, v2);
    transparent_crc(*(int32_t *)(v3 + 0x322f), v3 + 1154, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3233), v3 + 1160, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x31eb), v2);
    return 0;
}

// Address range: 0x804a15c - 0x804a160
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a15c
    return result;
}

// Address range: 0x804a160 - 0x804a164
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804a160
    int32_t result; // 0x804a160
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
