//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x35ee));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c6a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bf9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x24ed));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x8049869
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804962f
    *(int16_t *)(v2 + 0x49f0) = (int16_t)a1;
    *(int32_t *)(v2 + 0x49f4) = a2;
    *(int16_t *)(v2 + 0x49f8) = (int16_t)a3;
    *(int32_t *)(v2 + 0x49fc) = a4;
    *(char *)(v2 + 0x4a00) = (char)a5;
    *(char *)(v2 + 0x4a01) = (char)a6;
    *(int32_t *)(v2 + 0x4a04) = a7;
    *(int32_t *)(v2 + 0x4a08) = a8;
    *(int32_t *)(v2 + 0x4eb0) = a9;
    *(char *)(v2 + 0x4a0c) = (char)a10;
    *(int32_t *)(v2 + 0x4a10) = a11;
    *(int32_t *)(v2 + 0x4a14) = a12;
    *(int32_t *)(v2 + 0x4a18) = a13;
    *(int16_t *)(v2 + 0x4a1c) = (int16_t)a14;
    *(int32_t *)(v2 + 0x4a20) = a15;
    *(char *)(v2 + 0x4a24) = (char)a16;
    *(int32_t *)(v2 + 0x4a28) = a17;
    *(int16_t *)(v2 + 0x4a2c) = (int16_t)a18;
    *(int16_t *)(v2 + 0x4a2e) = (int16_t)a19;
    *(int32_t *)(v2 + 0x4a30) = a20;
    *(int16_t *)(v2 + 0x4a34) = (int16_t)a21;
    *(int32_t *)(v2 + 0x4a38) = a22;
    *(int32_t *)(v2 + 0x4a3c) = a23;
    *(char *)(v2 + 0x4a40) = (char)a24;
    *(int16_t *)(v2 + 0x4a42) = (int16_t)a25;
    *(int32_t *)(v2 + 0x4a44) = a26;
    *(int32_t *)(v2 + 0x4a48) = a27;
    *(int32_t *)(v2 + 0x4a4c) = a28;
    *(int32_t *)(v2 + 0x4a50) = a29;
    *(int32_t *)(v2 + 0x4a54) = a30;
    *(char *)(v2 + 0x4a58) = (char)a31;
    *(int32_t *)(v2 + 0x4a5c) = a32;
    *(int32_t *)(v2 + 0x4a60) = a33;
    *(int32_t *)(v2 + 0x4a64) = a34;
    *(int32_t *)(v2 + 0x4a68) = a35;
    *(int32_t *)(v2 + 0x4a6c) = a36;
    *(int32_t *)(v2 + 0x4a70) = a37;
    *(int32_t *)(v2 + 0x4a74) = a38;
    *(int32_t *)(v2 + 0x4a78) = a39;
    return 0;
}

// Address range: 0x8049869 - 0x804b4c7
int32_t func_1(void) {
    // 0x804b3b9
    int32_t v1; // 0x8049869
    __x86_get_pc_thunk_ax(v1);
    set_var(-0x30d2, 8, 1300, 1, 24, 15, 8, -0x4d16f179, 0, 82, 0x5a14429f, -7, 6, -3, 0x480e9667, 1, -0x43b810f, 0x165e, 3327, -0x66b435ae, 0x619b, -0x6edf43de, -7, -127, 0x5831, 2, 0x27a3c4ab, 9, 0x7d05b84a, 1, 47, 0xa700e2, -1, 0, 0x7f397508, 0x14fbd77b, -1, -1, -0x336b8f5f);
    return -3;
}

// Address range: 0x804b4c7 - 0x804b9cf
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804b4f0
    int32_t v3; // 0x804b4c7
    if (v1 == (char **)2) {
        // 0x804b4f2
        int32_t v4; // 0x804b4c7
        int32_t str = *(int32_t *)(v4 + 4); // 0x804b4f8
        v2 = strcmp((char *)str, (char *)(v3 + 1498)) == 0;
    }
    // 0x804b518
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b46), v3 + 1500, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b4a), v3 + 1504, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b4e), v3 + 1509, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b52), v3 + 1514, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b56), v3 + 1519, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b57), v3 + 1524, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b5a), v3 + 1529, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b5e), v3 + 1534, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3006), v3 + 1539, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b62), v3 + 1544, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b66), v3 + 1550, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b6a), v3 + 1556, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b6e), v3 + 1562, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b72), v3 + 1568, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b76), v3 + 1574, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b7a), v3 + 1580, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b7e), v3 + 1586, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b82), v3 + 1592, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b84), v3 + 1598, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b86), v3 + 1604, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b8a), v3 + 1610, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b8e), v3 + 1616, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b92), v3 + 1622, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b96), v3 + 1628, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b98), v3 + 1634, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b9a), v3 + 1640, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b9e), v3 + 1646, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ba2), v3 + 1652, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ba6), v3 + 1658, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2baa), v3 + 1664, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2bae), v3 + 1670, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bb2), v3 + 1676, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bb6), v3 + 1682, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bba), v3 + 1688, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bbe), v3 + 1694, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bc2), v3 + 1700, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bc6), v3 + 1706, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bca), v3 + 1712, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bce), v3 + 1718, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2b42), v2);
    return 0;
}

// Address range: 0x804b9cf - 0x804b9d3
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804b9cf
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
