//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x2c8e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x1b8d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497fb
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x4e70) = a1;
    *(int32_t *)(v5 + 0x49f0) = a2;
    *(int32_t *)(v5 + 0x49f4) = a3;
    *(int32_t *)(v5 + 0x49f8) = a4;
    *(char *)(v5 + 0x49fc) = (char)a5;
    *(int16_t *)(v5 + 0x49fe) = (int16_t)a6;
    *(int32_t *)(v5 + 0x4a00) = a7;
    *(int32_t *)(v5 + 0x4a04) = a8;
    *(int16_t *)(v5 + 0x4a08) = (int16_t)a9;
    *(char *)(v5 + 0x4a0a) = (char)a10;
    *(int32_t *)(v5 + 0x4a0c) = a11;
    *(int32_t *)(v5 + 0x4a10) = a12;
    *(char *)(v5 + 0x4a14) = (char)a13;
    *(int32_t *)(v5 + 0x4e74) = a14;
    *(int32_t *)(v5 + 0x4a18) = a15;
    *(char *)(v5 + 0x4a1c) = (char)a16;
    *(char *)(v5 + 0x4a1d) = (char)a17;
    *(int16_t *)(v5 + 0x4e78) = (int16_t)a18;
    *(int32_t *)(v5 + 0x4a20) = a19;
    *(int16_t *)(v5 + 0x4a24) = (int16_t)a20;
    *(int32_t *)(v5 + 0x4a28) = a21;
    *(char *)(v5 + 0x4a2c) = (char)a22;
    *(char *)(v5 + 0x4a2d) = (char)a23;
    *(char *)(v5 + 0x4a2e) = (char)a24;
    *(int32_t *)(v5 + 0x4a30) = a25;
    *(char *)(v5 + 0x4a34) = (char)a26;
    *(int32_t *)(v5 + 0x4e7c) = a27;
    *(char *)(v5 + 0x4e80) = (char)a28;
    return 0;
}

// Address range: 0x80497fb - 0x804ac7c
int32_t func_1(void) {
    // 0x80497fb
    int32_t v1; // 0x80497fb
    __x86_get_pc_thunk_ax(v1);
    set_var(0, 1, 3, 1, -83, 1, 0x2c87a751, 0x1175c875, 0x44db, -104, 0x757037a9, -0x40298ab0, 75, 0, 0x7bcd1f54, 43, 75, 0, -6, 0x418d, 5, -31, 77, 122, 0x1b0b802a, 97, 0, 0);
    return 0x2c87a751;
}

// Address range: 0x804ac7c - 0x804b074
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804aca5
    int32_t v3; // 0x804ac7c
    if (v1 == (char **)2) {
        // 0x804aca7
        int32_t v4; // 0x804ac7c
        int32_t str = *(int32_t *)(v4 + 4); // 0x804acad
        v2 = strcmp((char *)str, (char *)(v3 + 1221)) == 0;
    }
    // 0x804accd
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x3811), v3 + 1223, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3391), v3 + 1227, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3395), v3 + 1231, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3399), v3 + 1235, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x339d), v3 + 1240, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x339f), v3 + 1245, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33a1), v3 + 1250, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33a5), v3 + 1255, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x33a9), v3 + 1260, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33ab), v3 + 1265, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33ad), v3 + 1270, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33b1), v3 + 1275, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33b5), v3 + 1280, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3815), v3 + 1286, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33b9), v3 + 1292, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33bd), v3 + 1298, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33be), v3 + 1304, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3819), v3 + 1310, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33c1), v3 + 1316, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x33c5), v3 + 1322, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33c9), v3 + 1328, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33cd), v3 + 1334, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33ce), v3 + 1340, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33cf), v3 + 1346, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33d1), v3 + 1352, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33d5), v3 + 1358, v2);
    transparent_crc(*(int32_t *)(v3 + 0x381d), v3 + 1364, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3821), v3 + 1370, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33d9), v3 + 1376, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x338d), v2);
    return 0;
}

// Address range: 0x804b074 - 0x804b078
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804b074
    return result;
}

// Address range: 0x804b078 - 0x804b07c
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804b078
    int32_t result; // 0x804b078
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
