//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x1d4e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c0a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3b99 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 3149));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804975e
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804962f
    *(int32_t *)(v2 + 0x39f0) = a1;
    *(int16_t *)(v2 + 0x39f4) = (int16_t)a2;
    *(int16_t *)(v2 + 0x39f6) = (int16_t)a3;
    *(int16_t *)(v2 + 0x39f8) = (int16_t)a4;
    *(int16_t *)(v2 + 0x39fa) = (int16_t)a5;
    *(char *)(v2 + 0x39fc) = (char)a6;
    *(int32_t *)(v2 + 0x3a00) = a7;
    *(int32_t *)(v2 + 0x3a04) = a8;
    *(char *)(v2 + 0x3a08) = (char)a9;
    *(int32_t *)(v2 + 0x3a0c) = a10;
    *(char *)(v2 + 0x3a10) = (char)a11;
    *(char *)(v2 + 0x3a11) = (char)a12;
    *(int32_t *)(v2 + 0x3a14) = a13;
    *(int32_t *)(v2 + 0x3a18) = a14;
    *(int32_t *)(v2 + 0x3e50) = a15;
    *(int32_t *)(v2 + 0x3a1c) = a16;
    *(int16_t *)(v2 + 0x3a20) = (int16_t)a17;
    *(int32_t *)(v2 + 0x3a24) = a18;
    *(int32_t *)(v2 + 0x3a28) = a19;
    return 0;
}

// Address range: 0x804975e - 0x8049e76
int32_t func_1(void) {
    // 0x804975e
    int32_t v1; // 0x804975e
    __x86_get_pc_thunk_ax(v1);
    int16_t v2 = 0; // 0x804975e
    int32_t v3 = -0x33e9820e; // 0x804975e
    uint16_t v4 = 5; // 0x804986f
    int32_t v5 = 7;
    char v6 = 1;
    int32_t v7 = 0;
    v4--;
    int32_t v8; // 0x804975e
    int32_t v9; // 0x804975e
    int32_t v10; // 0x804975e
    int16_t v11; // 0x804975e
    int16_t v12; // 0x804975e
    int32_t v13; // 0x804975e
    char v14; // 0x804975e
    int32_t v15; // 0x804975e
    char v16; // 0x804975e
    char v17; // 0x804975e
    int32_t v18; // 0x804975e
    int32_t v19; // 0x804975e
    int32_t v20; // 0x804975e
    int32_t v21; // 0x804975e
    int32_t v22; // 0x804975e
    int64_t v23; // 0x8049a95
    int64_t v24; // 0x8049aa0
    int32_t v25; // 0x8049caf
    int16_t v26; // 0x804975e
    // 0x8049c50
    v25 = v3 - (int32_t)(v7 == 0);
    v26 = 0x136f;
    v8 = v4;
    v11 = v26;
    v10 = v26;
    v12 = 0x2614;
    v13 = -8;
    v14 = v25 < 0 == ((v25 ^ -0x80000000) & v3) < 0 ? 3 : 2;
    v15 = v5 ^ 1;
    v16 = v6 - 1;
    v17 = -9;
    v18 = 0x7ffb;
    v19 = 0;
    v20 = 0;
    v21 = v3;
    int32_t v27 = v20;
    int32_t v28 = v19;
    int32_t v29 = v18;
    char v30 = v17;
    char v31 = v16;
    int32_t v32 = v15;
    char v33 = v14;
    int32_t v34 = v13;
    int16_t v35 = v12;
    int32_t v36 = v7 + 1; // 0x8049da5
    v2 = v36;
    v3 = v21;
    while (v36 != 50) {
        // 0x8049844
        v5 = v32;
        v6 = v31;
        v7 = v36;
        v4--;
        if (v8 == 0) {
            // 0x8049a78
            v22 = v4;
            v9 = 0x1000000 * v22;
            v23 = (0x100000000 * (int64_t)(v9 >> 31) | (int64_t)(v9 / 0x1000000)) / (int64_t)(0x1000000 * v7 / 0x1000000);
            v24 = (v23 & 0xfffe) == 0 ? v23 : 0;
            v8 = v22;
            v11 = -0x36df;
            v10 = 0xc921;
            v12 = v2;
            v13 = (v4 % 2 ^ (int16_t)v24) & v2;
            v14 = v33;
            v15 = v5;
            v16 = v6;
            v17 = v30;
            v18 = v29;
            v19 = v28;
            v20 = v27;
            v21 = 0;
        } else {
            // 0x8049c50
            v25 = v3 - (int32_t)(v7 == 0);
            v26 = v11 + 1;
            v8 = v4;
            v11 = v26;
            v10 = v26;
            v12 = v35;
            v13 = v34;
            v14 = v25 < 0 == ((v25 ^ -0x80000000) & v3) < 0 ? 3 : 2;
            v15 = v5 ^ 1;
            v16 = v6 - 1;
            v17 = -9;
            v18 = 0x7ffb;
            v19 = 0;
            v20 = 0;
            v21 = v3;
        }
        // 0x8049da5
        v27 = v20;
        v28 = v19;
        v29 = v18;
        v30 = v17;
        v31 = v16;
        v32 = v15;
        v33 = v14;
        v34 = v13;
        v35 = v12;
        v36 = v7 + 1;
        v2 = v36;
        v3 = v21;
    }
    // 0x8049db3
    set_var(50, 0xffd3, v10, (int32_t)v35, 0x10000 * v34 / 0x10000, (int32_t)v33, v32, -0x3a0f847a, (int32_t)v31, -9, 1, (int32_t)v30, v29, v28, 0, v27, 0x202e, -0x3eea97d9, 0);
    return 250;
}

// Address range: 0x8049e76 - 0x804a132
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049e9f
    int32_t v3; // 0x8049e76
    if (v1 == (char **)2) {
        // 0x8049ea1
        int32_t v4; // 0x8049e76
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049ea7
        v2 = strcmp((char *)str, (char *)(v3 + 907)) == 0;
    }
    // 0x8049ec7
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x3197), v3 + 909, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x319b), v3 + 913, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x319d), v3 + 917, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x319f), v3 + 922, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31a1), v3 + 927, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31a3), v3 + 932, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31a7), v3 + 937, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31ab), v3 + 942, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31af), v3 + 947, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31b3), v3 + 953, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31b7), v3 + 959, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31b8), v3 + 965, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31bb), v3 + 971, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31bf), v3 + 977, v2);
    transparent_crc(*(int32_t *)(v3 + 0x35f7), v3 + 983, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31c3), v3 + 989, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31c7), v3 + 995, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31cb), v3 + 1001, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31cf), v3 + 1007, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x3193), v2);
    return 0;
}

// Address range: 0x804a132 - 0x804a136
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a132
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
