//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x298e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x188d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497fb
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int16_t *)(v5 + 0x39f2) = (int16_t)a1;
    *(char *)(v5 + 0x39f4) = (char)a2;
    *(int32_t *)(v5 + 0x39f8) = a3;
    *(int32_t *)(v5 + 0x39fc) = a4;
    *(char *)(v5 + 0x3a00) = (char)a5;
    *(int32_t *)(v5 + 0x3a04) = a6;
    *(int16_t *)(v5 + 0x3a08) = (int16_t)a7;
    *(char *)(v5 + 0x3a0a) = (char)a8;
    *(char *)(v5 + 0x3a0b) = (char)a9;
    *(int32_t *)(v5 + 0x3a0c) = a10;
    *(int32_t *)(v5 + 0x3a10) = a11;
    *(char *)(v5 + 0x3a14) = (char)a12;
    *(int32_t *)(v5 + 0x3a18) = a13;
    *(int32_t *)(v5 + 0x3a1c) = a14;
    *(char *)(v5 + 0x3a20) = (char)a15;
    *(char *)(v5 + 0x3a21) = (char)a16;
    *(int16_t *)(v5 + 0x3a22) = (int16_t)a17;
    *(int32_t *)(v5 + 0x3a24) = a18;
    *(int32_t *)(v5 + 0x3a28) = a19;
    *(int32_t *)(v5 + 0x3a2c) = a20;
    *(char *)(v5 + 0x3a30) = (char)a21;
    *(int32_t *)(v5 + 0x3a34) = a22;
    *(char *)(v5 + 0x3a38) = (char)a23;
    *(int16_t *)(v5 + 0x3e70) = (int16_t)a24;
    *(char *)(v5 + 0x3a39) = (char)a25;
    *(int32_t *)(v5 + 0x3a3c) = a26;
    *(int32_t *)(v5 + 0x3e74) = a27;
    *(int32_t *)(v5 + 0x3a40) = a28;
    return 0;
}

// Address range: 0x80497fb - 0x804a940
int32_t func_1(void) {
    // 0x80497fb
    int32_t v1; // 0x80497fb
    __x86_get_pc_thunk_ax(v1);
    set_var(13, 0, -0x27942518, -6, 1, -2, 9, 0, 199, -39, 0, 76, 49, 0, 227, -1, 0xffb3, 0x6d265171, 0x13cd0db1, -1, -77, 0x490424ae, 0, 0, 250, 0, 0, 0x1bb1884e);
    return -0x68e79848;
}

// Address range: 0x804a940 - 0x804ad6e
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a969
    int32_t v3; // 0x804a940
    if (v1 == (char **)2) {
        // 0x804a96b
        int32_t v4; // 0x804a940
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a971
        v2 = strcmp((char *)str, (char *)(v3 + 1283)) == 0;
    }
    // 0x804a991
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x26cd), v3 + 1285, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x26cf), v3 + 1289, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26d1), v3 + 1294, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26d5), v3 + 1299, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26d9), v3 + 1304, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26dd), v3 + 1309, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26e1), v3 + 1314, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x26e5), v3 + 1319, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26e7), v3 + 1324, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26e8), v3 + 1329, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26e9), v3 + 1334, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26ed), v3 + 1339, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26f1), v3 + 1344, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26f5), v3 + 1350, v2);
    transparent_crc(254, v3 + 1356, v2);
    transparent_crc(*(int32_t *)(v3 + 0x26f9), v3 + 1362, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26fd), v3 + 1368, v2);
    transparent_crc(-9, v3 + 1374, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x26fe), v3 + 1380, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x26ff), v3 + 1386, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2701), v3 + 1392, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2705), v3 + 1398, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2709), v3 + 1404, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x270d), v3 + 1410, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2711), v3 + 1416, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2715), v3 + 1422, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b4d), v3 + 1428, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2716), v3 + 1434, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2719), v3 + 1440, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b51), v3 + 1446, v2);
    transparent_crc(*(int32_t *)(v3 + 0x271d), v3 + 1452, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x26c9), v2);
    return 0;
}

// Address range: 0x804ad6e - 0x804ad72
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804ad6e
    return result;
}

// Address range: 0x804ad72 - 0x804ad76
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804ad72
    int32_t result; // 0x804ad72
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
