//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x2d8e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c4a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bd9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x1c8d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x8049821
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804962f
    *(int32_t *)(v2 + 0x49f0) = a1;
    *(int32_t *)(v2 + 0x49f4) = a2;
    *(int32_t *)(v2 + 0x49f8) = a3;
    *(int16_t *)(v2 + 0x49fc) = (int16_t)a4;
    *(int16_t *)(v2 + 0x49fe) = (int16_t)a5;
    *(int32_t *)(v2 + 0x4a00) = a6;
    *(int32_t *)(v2 + 0x4e90) = a7;
    *(char *)(v2 + 0x4a04) = (char)a8;
    *(int16_t *)(v2 + 0x4a06) = (int16_t)a9;
    *(int32_t *)(v2 + 0x4a08) = a10;
    *(int32_t *)(v2 + 0x4a0c) = a11;
    *(int32_t *)(v2 + 0x4a10) = a12;
    *(char *)(v2 + 0x4e94) = (char)a13;
    *(char *)(v2 + 0x4a14) = (char)a14;
    *(int32_t *)(v2 + 0x4a18) = a15;
    *(int16_t *)(v2 + 0x4a1c) = (int16_t)a16;
    *(int32_t *)(v2 + 0x4a20) = a17;
    *(int32_t *)(v2 + 0x4a24) = a18;
    *(int32_t *)(v2 + 0x4a28) = a19;
    *(int32_t *)(v2 + 0x4a2c) = a20;
    *(char *)(v2 + 0x4a30) = (char)a21;
    *(int16_t *)(v2 + 0x4a32) = (int16_t)a22;
    *(int32_t *)(v2 + 0x4e98) = a23;
    *(char *)(v2 + 0x4a34) = (char)a24;
    *(int16_t *)(v2 + 0x4a36) = (int16_t)a25;
    *(char *)(v2 + 0x4e9c) = (char)a26;
    *(int32_t *)(v2 + 0x4a38) = a27;
    *(int32_t *)(v2 + 0x4a3c) = a28;
    *(int32_t *)(v2 + 0x4a40) = a29;
    *(int16_t *)(v2 + 0x4a44) = (int16_t)a30;
    *(int32_t *)(v2 + 0x4a48) = a31;
    *(int32_t *)(v2 + 0x4a4c) = a32;
    *(int32_t *)(v2 + 0x4a50) = a33;
    return 0;
}

// Address range: 0x8049821 - 0x804ad0f
int32_t func_1(void) {
    // 0x804ad07
    int32_t v1; // 0x8049821
    __x86_get_pc_thunk_ax(v1);
    set_var(0x17ca0029, 1, -0x231a0eb7, -3, 1, 1, 0, 23, 2, -0x7af4, -0x23cb8bc5, 0xa761eae, 0, -89, -93, 5, 1, 1, 6, 6, 43, 0xfff7, 0, 1, -1, 0, -10, 0x12770150, 6, 0xffff, 0x5f07cb1, 3, 0x1f390613);
    return 0;
}

// Address range: 0x804ad0f - 0x804b175
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804ad38
    int32_t v3; // 0x804ad0f
    if (v1 == (char **)2) {
        // 0x804ad3a
        int32_t v4; // 0x804ad0f
        int32_t str = *(int32_t *)(v4 + 4); // 0x804ad40
        v2 = strcmp((char *)str, (char *)(v3 + 1330)) == 0;
    }
    // 0x804ad60
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x32fe), v3 + 1332, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3302), v3 + 1336, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3306), v3 + 1341, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x330a), v3 + 1346, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x330c), v3 + 1351, v2);
    transparent_crc(*(int32_t *)(v3 + 0x330e), v3 + 1356, v2);
    transparent_crc(*(int32_t *)(v3 + 0x379e), v3 + 1361, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3312), v3 + 1366, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3314), v3 + 1371, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3316), v3 + 1376, v2);
    transparent_crc(*(int32_t *)(v3 + 0x331a), v3 + 1382, v2);
    transparent_crc(*(int32_t *)(v3 + 0x331e), v3 + 1388, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x37a2), v3 + 1394, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3322), v3 + 1400, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3326), v3 + 1406, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x332a), v3 + 1412, v2);
    transparent_crc(*(int32_t *)(v3 + 0x332e), v3 + 1418, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3332), v3 + 1424, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3336), v3 + 1430, v2);
    transparent_crc(*(int32_t *)(v3 + 0x333a), v3 + 1436, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x333e), v3 + 1442, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3340), v3 + 1448, v2);
    transparent_crc(*(int32_t *)(v3 + 0x37a6), v3 + 1454, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3342), v3 + 1460, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3344), v3 + 1466, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x37aa), v3 + 1472, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3346), v3 + 1478, v2);
    transparent_crc(*(int32_t *)(v3 + 0x334a), v3 + 1484, v2);
    transparent_crc(*(int32_t *)(v3 + 0x334e), v3 + 1490, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3352), v3 + 1496, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3356), v3 + 1502, v2);
    transparent_crc(*(int32_t *)(v3 + 0x335a), v3 + 1508, v2);
    transparent_crc(*(int32_t *)(v3 + 0x335e), v3 + 1514, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x32fa), v2);
    return 0;
}

// Address range: 0x804b175 - 0x804b179
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804b175
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
