//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x21ae));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c0a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3b99 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x10ad));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804976a
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x39f0) = a1;
    *(int32_t *)(v5 + 0x39f4) = a2;
    *(int32_t *)(v5 + 0x39f8) = a3;
    *(int32_t *)(v5 + 0x39fc) = a4;
    *(int16_t *)(v5 + 0x3a00) = (int16_t)a5;
    *(char *)(v5 + 0x3a02) = (char)a6;
    *(int16_t *)(v5 + 0x3a04) = (int16_t)a7;
    *(int16_t *)(v5 + 0x3a06) = (int16_t)a8;
    *(char *)(v5 + 0x3a08) = (char)a9;
    *(int16_t *)(v5 + 0x3a0a) = (int16_t)a10;
    *(int32_t *)(v5 + 0x3a0c) = a11;
    *(int16_t *)(v5 + 0x3a10) = (int16_t)a12;
    *(int32_t *)(v5 + 0x3a14) = a13;
    *(int32_t *)(v5 + 0x3a18) = a14;
    *(int16_t *)(v5 + 0x3a1c) = (int16_t)a15;
    *(int16_t *)(v5 + 0x3a1e) = (int16_t)a16;
    *(int32_t *)(v5 + 0x3a20) = a17;
    *(int16_t *)(v5 + 0x3a24) = (int16_t)a18;
    return 0;
}

// Address range: 0x804976a - 0x804a2e2
int32_t func_1(void) {
    // 0x804976a
    int32_t v1; // 0x804976a
    __x86_get_pc_thunk_ax(v1);
    set_var(6, 19, -1, 1, 6, -8, -0x7e7a, 4, 136, 1, -0x3e5ef048, 0x1296, 0x2485d133, -9, 0xffff, 0x3155, 0x7fae0a69, 0x6d56);
    return 128;
}

// Address range: 0x804a2e2 - 0x804a590
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a30b
    int32_t v3; // 0x804a2e2
    if (v1 == (char **)2) {
        // 0x804a30d
        int32_t v4; // 0x804a2e2
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a313
        v2 = strcmp((char *)str, (char *)(v3 + 895)) == 0;
    }
    // 0x804a333
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x2d2b), v3 + 897, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d2f), v3 + 901, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d33), v3 + 905, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d37), v3 + 910, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d3b), v3 + 915, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2d3d), v3 + 920, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d3f), v3 + 925, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d41), v3 + 930, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2d43), v3 + 935, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d45), v3 + 941, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d47), v3 + 947, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d4b), v3 + 953, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d4f), v3 + 959, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d53), v3 + 965, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d57), v3 + 971, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d59), v3 + 977, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2d5b), v3 + 983, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2d5f), v3 + 989, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2d27), v2);
    return 0;
}

// Address range: 0x804a590 - 0x804a594
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a590
    return result;
}

// Address range: 0x804a594 - 0x804a598
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804a594
    int32_t result; // 0x804a594
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
