//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x3ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x1b3e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x2c0a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x2b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x2b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x2b99 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x2b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 2621));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x8049757
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(char *)(v5 + 0x29f0) = (char)a1;
    *(int32_t *)(v5 + 0x29f4) = a2;
    *(int32_t *)(v5 + 0x29f8) = a3;
    *(char *)(v5 + 0x29fc) = (char)a4;
    *(char *)(v5 + 0x29fd) = (char)a5;
    *(char *)(v5 + 0x29fe) = (char)a6;
    *(int32_t *)(v5 + 0x2a00) = a7;
    *(char *)(v5 + 0x2a04) = (char)a8;
    *(int16_t *)(v5 + 0x2a06) = (int16_t)a9;
    *(int32_t *)(v5 + 0x2a08) = a10;
    *(char *)(v5 + 0x2e50) = (char)a11;
    *(int32_t *)(v5 + 0x2a0c) = a12;
    *(int16_t *)(v5 + 0x2a10) = (int16_t)a13;
    *(char *)(v5 + 0x2e51) = (char)a14;
    *(int32_t *)(v5 + 0x2a14) = a15;
    *(int16_t *)(v5 + 0x2a18) = (int16_t)a16;
    *(int32_t *)(v5 + 0x2e54) = a17;
    return 0;
}

// Address range: 0x8049757 - 0x8049c90
int32_t func_1(void) {
    // 0x8049757
    int32_t v1; // 0x8049757
    __x86_get_pc_thunk_ax(v1);
    set_var(-2, -1, 4, 255, 1, 51, 0x55dfc961, 131, 0x2c37, 0x70ef1a53, 0, -1, 0x7008, 0, 1, 0x2e66, 0);
    return -1;
}

// Address range: 0x8049c90 - 0x8049f20
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049cb9
    int32_t v3; // 0x8049c90
    if (v1 == (char **)2) {
        // 0x8049cbb
        int32_t v4; // 0x8049c90
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049cc1
        v2 = strcmp((char *)str, (char *)(v3 + 865)) == 0;
    }
    // 0x8049ce1
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(char *)(v3 + 0x237d), v3 + 867, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2381), v3 + 872, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2385), v3 + 877, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2389), v3 + 882, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x238a), v3 + 887, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x238b), v3 + 892, v2);
    transparent_crc(*(int32_t *)(v3 + 0x238d), v3 + 897, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2391), v3 + 903, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2393), v3 + 909, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2395), v3 + 915, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x27dd), v3 + 921, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2399), v3 + 927, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x239d), v3 + 933, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x27de), v3 + 939, v2);
    transparent_crc(*(int32_t *)(v3 + 0x23a1), v3 + 945, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x23a5), v3 + 951, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27e1), v3 + 957, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2379), v2);
    return 0;
}

// Address range: 0x8049f20 - 0x8049f24
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x8049f20
    return result;
}

// Address range: 0x8049f24 - 0x8049f28
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x8049f24
    int32_t result; // 0x8049f24
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
