//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x6ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x462e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x5c4a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x5b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x5b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x5bd9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x5b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x352d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804990b
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(char *)(v5 + 0x59ed) = (char)a1;
    *(int16_t *)(v5 + 0x59ef) = (int16_t)a2;
    *(int16_t *)(v5 + 0x59f1) = (int16_t)a3;
    *(int32_t *)(v5 + 0x5e8d) = a4;
    *(int32_t *)(v5 + 0x59f5) = a5;
    *(char *)(v5 + 0x59f9) = (char)a6;
    *(int32_t *)(v5 + 0x59fd) = a7;
    *(int16_t *)(v5 + 0x5a01) = (int16_t)a8;
    *(int32_t *)(v5 + 0x5a05) = a9;
    *(int32_t *)(v5 + 0x5e91) = a10;
    *(int32_t *)(v5 + 0x5a09) = a11;
    *(int32_t *)(v5 + 0x5a0d) = a12;
    *(int32_t *)(v5 + 0x5a11) = a13;
    *(int16_t *)(v5 + 0x5a15) = (int16_t)a14;
    *(int32_t *)(v5 + 0x5a19) = a15;
    *(int32_t *)(v5 + 0x5a1d) = a16;
    *(int32_t *)(v5 + 0x5a21) = a17;
    *(int32_t *)(v5 + 0x5a25) = a18;
    *(char *)(v5 + 0x5a29) = (char)a19;
    *(char *)(v5 + 0x5a2a) = (char)a20;
    *(int32_t *)(v5 + 0x5a2d) = a21;
    *(int32_t *)(v5 + 0x5e95) = a22;
    *(int32_t *)(v5 + 0x5a31) = a23;
    *(int32_t *)(v5 + 0x5a35) = a24;
    *(int32_t *)(v5 + 0x5a39) = a25;
    *(int16_t *)(v5 + 0x5a3d) = (int16_t)a26;
    *(int16_t *)(v5 + 0x5a3f) = (int16_t)a27;
    *(int16_t *)(v5 + 0x5a41) = (int16_t)a28;
    *(int16_t *)(v5 + 0x5a43) = (int16_t)a29;
    *(int16_t *)(v5 + 0x5a45) = (int16_t)a30;
    *(char *)(v5 + 0x5a47) = (char)a31;
    *(int16_t *)(v5 + 0x5a49) = (int16_t)a32;
    *(int32_t *)(v5 + 0x5a4d) = a33;
    *(char *)(v5 + 0x5a51) = (char)a34;
    *(char *)(v5 + 0x5a52) = (char)a35;
    *(char *)(v5 + 0x5a53) = (char)a36;
    *(int32_t *)(v5 + 0x5e99) = a37;
    *(char *)(v5 + 0x5a54) = (char)a38;
    *(int16_t *)(v5 + 0x5a55) = (int16_t)a39;
    return 0;
}

// Address range: 0x804990b - 0x804c4ea
int32_t func_1(void) {
    // 0x804990b
    int32_t v1; // 0x804990b
    __x86_get_pc_thunk_ax(v1);
    set_var(112, 112, 1, 0, -0x31219595, -37, 1, 1, 0x2d1e5678, 1, 0, -1, 2341, 0x28aa, -0x2476fde8, 1, -0x69a1cb83, -1, 138, -1, 0x12f7a823, 0, -4, -0x7a818f3b, -0x36623aed, 0xffff, -0x2a55, 0xffff, 6, 0xf343, 8, 0xffff, -1, 160, 4, 42, 0, 11, 0x48bf);
    return 0x28aa;
}

// Address range: 0x804c4ea - 0x804ca14
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804c513
    int32_t v3; // 0x804c4ea
    if (v1 == (char **)2) {
        // 0x804c515
        int32_t v4; // 0x804c4ea
        int32_t str = *(int32_t *)(v4 + 4); // 0x804c51b
        v2 = strcmp((char *)str, (char *)(v3 + 1527)) == 0;
    }
    // 0x804c53b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(char *)(v3 + 0x2b23), v3 + 1529, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b25), v3 + 1533, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b27), v3 + 1538, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2fc3), v3 + 1543, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b2b), v3 + 1548, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b2f), v3 + 1553, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b33), v3 + 1558, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b37), v3 + 1563, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b3b), v3 + 1568, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2fc7), v3 + 1573, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b3f), v3 + 1578, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b43), v3 + 1583, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b47), v3 + 1588, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b4b), v3 + 1594, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b4f), v3 + 1600, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b53), v3 + 1606, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b57), v3 + 1612, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b5b), v3 + 1618, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b5f), v3 + 1624, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b60), v3 + 1630, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b63), v3 + 1636, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2fcb), v3 + 1642, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b67), v3 + 1648, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b6b), v3 + 1654, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b6f), v3 + 1660, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b73), v3 + 1666, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b75), v3 + 1672, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b77), v3 + 1678, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b79), v3 + 1684, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b7b), v3 + 1690, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b7d), v3 + 1696, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b7f), v3 + 1702, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b83), v3 + 1708, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b87), v3 + 1714, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b88), v3 + 1720, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b89), v3 + 1726, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2fcf), v3 + 1732, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b8a), v3 + 1738, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b8b), v3 + 1744, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2b1f), v2);
    return 0;
}

// Address range: 0x804ca14 - 0x804ca18
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804ca14
    return result;
}

// Address range: 0x804ca18 - 0x804ca1c
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804ca18
    int32_t result; // 0x804ca18
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
