//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x28de));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x17dd));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497e6
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x39f0) = a1;
    *(int32_t *)(v5 + 0x39f4) = a2;
    *(int32_t *)(v5 + 0x39f8) = a3;
    *(char *)(v5 + 0x39fc) = (char)a4;
    *(int32_t *)(v5 + 0x3a00) = a5;
    *(int32_t *)(v5 + 0x3a04) = a6;
    *(char *)(v5 + 0x3a08) = (char)a7;
    *(char *)(v5 + 0x3a09) = (char)a8;
    *(int32_t *)(v5 + 0x3a0c) = a9;
    *(int32_t *)(v5 + 0x3a10) = a10;
    *(int32_t *)(v5 + 0x3a14) = a11;
    *(int32_t *)(v5 + 0x3a18) = a12;
    *(char *)(v5 + 0x3a1c) = (char)a13;
    *(char *)(v5 + 0x3a1d) = (char)a14;
    *(int32_t *)(v5 + 0x3e70) = a15;
    *(char *)(v5 + 0x3a1e) = (char)a16;
    *(int32_t *)(v5 + 0x3e74) = a17;
    *(char *)(v5 + 0x3a1f) = (char)a18;
    *(int32_t *)(v5 + 0x3a20) = a19;
    *(int16_t *)(v5 + 0x3a24) = (int16_t)a20;
    *(int32_t *)(v5 + 0x3a28) = a21;
    *(int32_t *)(v5 + 0x3a2c) = a22;
    *(int16_t *)(v5 + 0x3a30) = (int16_t)a23;
    *(int32_t *)(v5 + 0x3a34) = a24;
    *(char *)(v5 + 0x3a38) = (char)a25;
    *(int32_t *)(v5 + 0x3a3c) = a26;
    *(int32_t *)(v5 + 0x3a40) = a27;
    *(char *)(v5 + 0x3e78) = (char)a28;
    *(int32_t *)(v5 + 0x3a44) = a29;
    *(char *)(v5 + 0x3a48) = (char)a30;
    return 0;
}

// Address range: 0x80497e6 - 0x804a8b6
int32_t func_1(void) {
    // 0x8049909
    int32_t v1; // 0x80497e6
    __x86_get_pc_thunk_ax(v1);
    set_var(-0x5750, 0, 0x7c6f1fdb, 65, 0x12c005d9, -0x26acd6ab, 1, 60, -42, 0x60f33e23, 0x63b2caa8, -0x5d2aca8b, 67, 168, 1328, -10, 0, 2, 0xbbb0, 0xbbb0, -0x37b7, 0x3b28269d, -1, 0x4c012c7d, 1, 0x1e73, -2, 0, 1, 109);
    return -2;
}

// Address range: 0x804a8b6 - 0x804acbe
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a8df
    int32_t v3; // 0x804a8b6
    if (v1 == (char **)2) {
        // 0x804a8e1
        int32_t v4; // 0x804a8b6
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a8e7
        v2 = strcmp((char *)str, (char *)(v3 + 1243)) == 0;
    }
    // 0x804a907
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x2757), v3 + 1245, v2);
    transparent_crc(*(int32_t *)(v3 + 0x275b), v3 + 1250, v2);
    transparent_crc(*(int32_t *)(v3 + 0x275f), v3 + 1255, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2763), v3 + 1260, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2767), v3 + 1265, v2);
    transparent_crc(*(int32_t *)(v3 + 0x276b), v3 + 1270, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x276f), v3 + 1275, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2770), v3 + 1280, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2773), v3 + 1285, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2777), v3 + 1290, v2);
    transparent_crc(*(int32_t *)(v3 + 0x277b), v3 + 1295, v2);
    transparent_crc(*(int32_t *)(v3 + 0x277f), v3 + 1300, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2783), v3 + 1305, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2784), v3 + 1310, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bd7), v3 + 1315, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2785), v3 + 1320, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2bdb), v3 + 1325, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2786), v3 + 1330, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2787), v3 + 1335, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x278b), v3 + 1341, v2);
    transparent_crc(*(int32_t *)(v3 + 0x278f), v3 + 1347, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2793), v3 + 1353, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2797), v3 + 1359, v2);
    transparent_crc(*(int32_t *)(v3 + 0x279b), v3 + 1365, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x279f), v3 + 1371, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27a3), v3 + 1377, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27a7), v3 + 1383, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2bdf), v3 + 1389, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27ab), v3 + 1395, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x27af), v3 + 1401, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2753), v2);
    return 0;
}

// Address range: 0x804acbe - 0x804acc2
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804acbe
    return result;
}

// Address range: 0x804acc2 - 0x804acc6
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804acc2
    int32_t result; // 0x804acc2
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
