//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x229e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x119d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804976a
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804962f
    *(int32_t *)(v2 + 0x39f0) = a1;
    *(int32_t *)(v2 + 0x39f4) = a2;
    *(int32_t *)(v2 + 0x39f8) = a3;
    *(int32_t *)(v2 + 0x39fc) = a4;
    *(int32_t *)(v2 + 0x3a00) = a5;
    *(char *)(v2 + 0x3a04) = (char)a6;
    *(int32_t *)(v2 + 0x3a08) = a7;
    *(int32_t *)(v2 + 0x3a0c) = a8;
    *(char *)(v2 + 0x3a10) = (char)a9;
    *(int32_t *)(v2 + 0x3a14) = a10;
    *(char *)(v2 + 0x3a18) = (char)a11;
    *(int16_t *)(v2 + 0x3a1a) = (int16_t)a12;
    *(int32_t *)(v2 + 0x3a1c) = a13;
    *(char *)(v2 + 0x3a20) = (char)a14;
    *(int32_t *)(v2 + 0x3a24) = a15;
    *(char *)(v2 + 0x3a28) = (char)a16;
    *(char *)(v2 + 0x3a29) = (char)a17;
    *(char *)(v2 + 0x3a2a) = (char)a18;
    *(int32_t *)(v2 + 0x3a2c) = a19;
    *(int16_t *)(v2 + 0x3a30) = (int16_t)a20;
    *(int32_t *)(v2 + 0x3a34) = a21;
    return 0;
}

// Address range: 0x804976a - 0x804a37e
int32_t func_1(void) {
    // 0x804976a
    int32_t v1; // 0x804976a
    __x86_get_pc_thunk_ax(v1);
    set_var(-1, 0xae9714a, 0, 0x5efb71fe, -85, 9, 1, -0x40d9e8f, 2, -1, 252, -10, 1, 58, -1, 54, 1, 255, -0x755a7cdd, 1, 1);
    return 1;
}

// Address range: 0x804a37e - 0x804a682
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a3a7
    int32_t v3; // 0x804a37e
    if (v1 == (char **)2) {
        // 0x804a3a9
        int32_t v4; // 0x804a37e
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a3af
        v2 = strcmp((char *)str, (char *)(v3 + 979)) == 0;
    }
    // 0x804a3cf
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x2c8f), v3 + 981, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2c93), v3 + 985, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2c97), v3 + 989, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2c9b), v3 + 993, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2c9f), v3 + 997, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ca3), v3 + 1002, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ca7), v3 + 1007, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2cab), v3 + 1012, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2caf), v3 + 1017, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2cb3), v3 + 1022, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2cb7), v3 + 1027, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2cb9), v3 + 1033, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2cbb), v3 + 1039, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2cbf), v3 + 1045, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2cc3), v3 + 1051, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2cc7), v3 + 1057, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2cc8), v3 + 1063, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2cc9), v3 + 1069, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ccb), v3 + 1075, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2ccf), v3 + 1081, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2cd3), v3 + 1087, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2c8b), v2);
    return 0;
}

// Address range: 0x804a682 - 0x804a686
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a682
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
