//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x321e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c4a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bd9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x211d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x8049888
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804962f
    *(int32_t *)(v2 + 0x49f0) = a1;
    *(char *)(v2 + 0x49f4) = (char)a2;
    *(int32_t *)(v2 + 0x49f8) = a3;
    *(int32_t *)(v2 + 0x49fc) = a4;
    *(int32_t *)(v2 + 0x4a00) = a5;
    *(int32_t *)(v2 + 0x4a04) = a6;
    *(char *)(v2 + 0x4a08) = (char)a7;
    *(char *)(v2 + 0x4a09) = (char)a8;
    *(char *)(v2 + 0x4a0a) = (char)a9;
    *(int32_t *)(v2 + 0x4a0c) = a10;
    *(int32_t *)(v2 + 0x4a10) = a11;
    *(int16_t *)(v2 + 0x4a14) = (int16_t)a12;
    *(int32_t *)(v2 + 0x4a18) = a13;
    *(int32_t *)(v2 + 0x4a1c) = a14;
    *(int32_t *)(v2 + 0x4a20) = a15;
    *(int32_t *)(v2 + 0x4a24) = a16;
    *(int32_t *)(v2 + 0x4e90) = a17;
    *(int16_t *)(v2 + 0x4a28) = (int16_t)a18;
    *(int32_t *)(v2 + 0x4a2c) = a19;
    *(char *)(v2 + 0x4a30) = (char)a20;
    *(int32_t *)(v2 + 0x4a34) = a21;
    *(int32_t *)(v2 + 0x4a38) = a22;
    *(int32_t *)(v2 + 0x4e94) = a23;
    *(int32_t *)(v2 + 0x4e98) = a24;
    *(int32_t *)(v2 + 0x4a3c) = a25;
    *(int32_t *)(v2 + 0x4a40) = a26;
    *(int16_t *)(v2 + 0x4a44) = (int16_t)a27;
    *(int32_t *)(v2 + 0x4a48) = a28;
    *(int32_t *)(v2 + 0x4a4c) = a29;
    *(int16_t *)(v2 + 0x4a50) = (int16_t)a30;
    *(int32_t *)(v2 + 0x4a54) = a31;
    *(char *)(v2 + 0x4a58) = (char)a32;
    *(int32_t *)(v2 + 0x4a5c) = a33;
    *(int16_t *)(v2 + 0x4a60) = (int16_t)a34;
    *(char *)(v2 + 0x4a62) = (char)a35;
    *(char *)(v2 + 0x4a63) = (char)a36;
    *(char *)(v2 + 0x4a64) = (char)a37;
    *(char *)(v2 + 0x4a65) = (char)a38;
    *(int32_t *)(v2 + 0x4a68) = a39;
    return 0;
}

// Address range: 0x8049888 - 0x804b0d2
int32_t func_1(void) {
    // 0x804a6bb
    int32_t v1; // 0x8049888
    __x86_get_pc_thunk_ax(v1);
    set_var(-1, 8, 1, -1, -18, 238, 8, 1, 0, 7, 0x5494f356, 0xfffe, 0x4812a85f, 4, -1, -0x77d56e53, 0, 6, 0xfff7, 84, -3, -3, 0, -45, -0x52b971ea, 0x4e4a0d11, -1, 0x313d4e5e, 7, 1, 0x41423176, 111, -0x450ecfa5, 2344, 1, 255, -1, 17, 0x1af7c589);
    return -1;
}

// Address range: 0x804b0d2 - 0x804b609
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804b0fb
    int32_t v3; // 0x804b0d2
    if (v1 == (char **)2) {
        // 0x804b0fd
        int32_t v4; // 0x804b0d2
        int32_t str = *(int32_t *)(v4 + 4); // 0x804b103
        v2 = strcmp((char *)str, (char *)(v3 + 1539)) == 0;
    }
    // 0x804b123
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x2f3b), v3 + 1541, v2);
    transparent_crc(-0x1e477eba, v3 + 1545, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f3f), v3 + 1550, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f43), v3 + 1555, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f47), v3 + 1560, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f4b), v3 + 1565, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f4f), v3 + 1570, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f53), v3 + 1575, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f54), v3 + 1580, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f55), v3 + 1585, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f57), v3 + 1591, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f5b), v3 + 1597, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2f5f), v3 + 1603, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f63), v3 + 1609, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f67), v3 + 1615, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f6b), v3 + 1621, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f6f), v3 + 1627, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33db), v3 + 1633, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2f73), v3 + 1639, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f77), v3 + 1645, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f7b), v3 + 1651, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f7f), v3 + 1657, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f83), v3 + 1663, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33df), v3 + 1669, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33e3), v3 + 1675, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f87), v3 + 1681, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f8b), v3 + 1687, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2f8f), v3 + 1693, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f93), v3 + 1699, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f97), v3 + 1705, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2f9b), v3 + 1711, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f9f), v3 + 1717, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2fa3), v3 + 1723, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2fa7), v3 + 1729, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2fab), v3 + 1735, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2fad), v3 + 1741, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2fae), v3 + 1747, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2faf), v3 + 1753, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2fb0), v3 + 1759, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2fb3), v3 + 1765, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2f37), v2);
    return 0;
}

// Address range: 0x804b609 - 0x804b60d
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804b609
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
