//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x397e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c4a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bd9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x287d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80498d7
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33, int32_t a34, int32_t a35, int32_t a36, int32_t a37, int32_t a38, int32_t a39) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int16_t *)(v5 + 0x49f0) = (int16_t)a1;
    *(int16_t *)(v5 + 0x49f2) = (int16_t)a2;
    *(int32_t *)(v5 + 0x49f4) = a3;
    *(int32_t *)(v5 + 0x49f8) = a4;
    *(char *)(v5 + 0x49fc) = (char)a5;
    *(int16_t *)(v5 + 0x49fe) = (int16_t)a6;
    *(char *)(v5 + 0x4a00) = (char)a7;
    *(int32_t *)(v5 + 0x4a04) = a8;
    *(int32_t *)(v5 + 0x4a08) = a9;
    *(int32_t *)(v5 + 0x4e90) = a10;
    *(int16_t *)(v5 + 0x4a0c) = (int16_t)a11;
    *(int32_t *)(v5 + 0x4a10) = a12;
    *(int16_t *)(v5 + 0x4a14) = (int16_t)a13;
    *(int16_t *)(v5 + 0x4a16) = (int16_t)a14;
    *(int16_t *)(v5 + 0x4a18) = (int16_t)a15;
    *(int32_t *)(v5 + 0x4a1c) = a16;
    *(int16_t *)(v5 + 0x4a20) = (int16_t)a17;
    *(char *)(v5 + 0x4e94) = (char)a18;
    *(int16_t *)(v5 + 0x4a22) = (int16_t)a19;
    *(int32_t *)(v5 + 0x4a24) = a20;
    *(int32_t *)(v5 + 0x4a28) = a21;
    *(int32_t *)(v5 + 0x4a2c) = a22;
    *(int32_t *)(v5 + 0x4a30) = a23;
    *(int32_t *)(v5 + 0x4e98) = a24;
    *(int32_t *)(v5 + 0x4a34) = a25;
    *(int16_t *)(v5 + 0x4a38) = (int16_t)a26;
    *(char *)(v5 + 0x4a3a) = (char)a27;
    *(int32_t *)(v5 + 0x4a3c) = a28;
    *(int16_t *)(v5 + 0x4a40) = (int16_t)a29;
    *(int16_t *)(v5 + 0x4a42) = (int16_t)a30;
    *(int32_t *)(v5 + 0x4a44) = a31;
    *(int16_t *)(v5 + 0x4a48) = (int16_t)a32;
    *(int32_t *)(v5 + 0x4a4c) = a33;
    *(int32_t *)(v5 + 0x4a50) = a34;
    *(int32_t *)(v5 + 0x4a54) = a35;
    *(int32_t *)(v5 + 0x4a58) = a36;
    *(int16_t *)(v5 + 0x4e9c) = (int16_t)a37;
    *(int32_t *)(v5 + 0x4a5c) = a38;
    *(int32_t *)(v5 + 0x4a60) = a39;
    return 0;
}

// Address range: 0x80498d7 - 0x804b84d
int32_t func_1(void) {
    // 0x80498d7
    int32_t v1; // 0x80498d7
    __x86_get_pc_thunk_ax(v1);
    set_var(0xfffb, -5, 0, -0x51b06244, 124, 0x99b5, 180, -116, 0x5f20, 0, 8, 0x9b59b1e, 0x6406, -0x7b86, 0xfffb, 7, 1, 0, 0x63ed, -1, 0x46a68022, 1, -0x6f8d, 0, 1, 0x255f, -1, 0x9e39cd, 1, 0xffff, 0x2bfac57b, -6, 9, 1, -4, -0x1426be06, 0, -0x72c0f268, -9);
    return 0xfffb;
}

// Address range: 0x804b84d - 0x804bd67
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804b876
    int32_t v3; // 0x804b84d
    if (v1 == (char **)2) {
        // 0x804b878
        int32_t v4; // 0x804b84d
        int32_t str = *(int32_t *)(v4 + 4); // 0x804b87e
        v2 = strcmp((char *)str, (char *)(v3 + 1508)) == 0;
    }
    // 0x804b89e
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27c0), v3 + 1510, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27c2), v3 + 1514, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27c4), v3 + 1519, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27c8), v3 + 1524, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x27cc), v3 + 1529, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27ce), v3 + 1534, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x27d0), v3 + 1539, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27d4), v3 + 1544, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27d8), v3 + 1549, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2c60), v3 + 1555, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27dc), v3 + 1561, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27e0), v3 + 1567, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27e4), v3 + 1573, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27e6), v3 + 1579, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27e8), v3 + 1585, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27ec), v3 + 1591, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27f0), v3 + 1597, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2c64), v3 + 1603, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x27f2), v3 + 1609, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27f4), v3 + 1615, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27f8), v3 + 1621, v2);
    transparent_crc(*(int32_t *)(v3 + 0x27fc), v3 + 1627, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2800), v3 + 1633, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2c68), v3 + 1639, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2804), v3 + 1645, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2808), v3 + 1651, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x280a), v3 + 1657, v2);
    transparent_crc(*(int32_t *)(v3 + 0x280c), v3 + 1663, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2810), v3 + 1669, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2812), v3 + 1675, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2814), v3 + 1681, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2818), v3 + 1687, v2);
    transparent_crc(*(int32_t *)(v3 + 0x281c), v3 + 1693, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2820), v3 + 1699, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2824), v3 + 1705, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2828), v3 + 1711, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2c6c), v3 + 1717, v2);
    transparent_crc(*(int32_t *)(v3 + 0x282c), v3 + 1723, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2830), v3 + 1729, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x27bc), v2);
    return 0;
}

// Address range: 0x804bd67 - 0x804bd6b
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804bd67
    return result;
}

// Address range: 0x804bd6b - 0x804bd6f
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804bd6b
    int32_t result; // 0x804bd6b
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
