//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x1dbe));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 3261));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x804982c
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x39f0) = a1;
    *(int32_t *)(v5 + 0x39f4) = a2;
    *(int32_t *)(v5 + 0x3e70) = a3;
    *(char *)(v5 + 0x39f8) = (char)a4;
    *(char *)(v5 + 0x39f9) = (char)a5;
    *(int16_t *)(v5 + 0x39fa) = (int16_t)a6;
    *(int32_t *)(v5 + 0x39fc) = a7;
    *(int32_t *)(v5 + 0x3a00) = a8;
    *(int16_t *)(v5 + 0x3a04) = (int16_t)a9;
    *(int16_t *)(v5 + 0x3a06) = (int16_t)a10;
    *(int16_t *)(v5 + 0x3a08) = (int16_t)a11;
    *(int16_t *)(v5 + 0x3a0a) = (int16_t)a12;
    *(int16_t *)(v5 + 0x3e74) = (int16_t)a13;
    *(char *)(v5 + 0x3a0c) = (char)a14;
    *(int32_t *)(v5 + 0x3a10) = a15;
    *(char *)(v5 + 0x3a14) = (char)a16;
    *(int32_t *)(v5 + 0x3a18) = a17;
    *(int32_t *)(v5 + 0x3a1c) = a18;
    *(int32_t *)(v5 + 0x3a20) = a19;
    *(int16_t *)(v5 + 0x3a24) = (int16_t)a20;
    *(int32_t *)(v5 + 0x3a28) = a21;
    *(char *)(v5 + 0x3a2c) = (char)a22;
    *(int16_t *)(v5 + 0x3a2e) = (int16_t)a23;
    *(char *)(v5 + 0x3a30) = (char)a24;
    *(int16_t *)(v5 + 0x3a32) = (int16_t)a25;
    *(char *)(v5 + 0x3a34) = (char)a26;
    *(char *)(v5 + 0x3a35) = (char)a27;
    return 0;
}

// Address range: 0x804982c - 0x8049de5
int32_t func_1(void) {
    // 0x804982c
    int32_t v1; // 0x804982c
    __x86_get_pc_thunk_ax(v1);
    set_var(0, 2, 0, 239, 0, 1895, 2, -1, 0x352b, 0x2630, -1, 2, 0, -2, -1, 255, 0x3271fe88, 0x21247b8c, 1, 1, -7, -7, -3, -17, -0x2a33, 251, 5);
    return 2;
}

// Address range: 0x8049de5 - 0x804a19d
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049e0e
    int32_t v3; // 0x8049de5
    if (v1 == (char **)2) {
        // 0x8049e10
        int32_t v4; // 0x8049de5
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049e16
        v2 = strcmp((char *)str, (char *)(v3 + 1164)) == 0;
    }
    // 0x8049e36
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x3228), v3 + 1166, v2);
    transparent_crc(*(int32_t *)(v3 + 0x322c), v3 + 1170, v2);
    transparent_crc(*(int32_t *)(v3 + 0x36a8), v3 + 1175, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3230), v3 + 1180, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3231), v3 + 1185, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3232), v3 + 1190, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3234), v3 + 1195, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3238), v3 + 1200, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x323c), v3 + 1205, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x323e), v3 + 1210, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3240), v3 + 1215, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3242), v3 + 1220, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x36ac), v3 + 1225, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3244), v3 + 1230, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3248), v3 + 1235, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x324c), v3 + 1240, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3250), v3 + 1246, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3254), v3 + 1252, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3258), v3 + 1258, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x325c), v3 + 1264, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3260), v3 + 1270, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3264), v3 + 1276, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3266), v3 + 1282, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3268), v3 + 1288, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x326a), v3 + 1294, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x326c), v3 + 1300, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x326d), v3 + 1306, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x3224), v2);
    return 0;
}

// Address range: 0x804a19d - 0x804a1a1
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a19d
    return result;
}

// Address range: 0x804a1a1 - 0x804a1a5
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804a1a1
    int32_t result; // 0x804a1a1
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
