//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x245e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c0a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3b99 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x135d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497fd
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x39f0) = a1;
    *(int16_t *)(v5 + 0x39f4) = (int16_t)a2;
    *(char *)(v5 + 0x39f6) = (char)a3;
    *(int32_t *)(v5 + 0x39f8) = a4;
    *(int16_t *)(v5 + 0x39fc) = (int16_t)a5;
    *(int32_t *)(v5 + 0x3e50) = a6;
    *(int16_t *)(v5 + 0x39fe) = (int16_t)a7;
    *(int16_t *)(v5 + 0x3a00) = (int16_t)a8;
    *(char *)(v5 + 0x3a02) = (char)a9;
    *(char *)(v5 + 0x3a03) = (char)a10;
    *(int16_t *)(v5 + 0x3a04) = (int16_t)a11;
    *(int32_t *)(v5 + 0x3a08) = a12;
    *(char *)(v5 + 0x3a0c) = (char)a13;
    *(int16_t *)(v5 + 0x3a0e) = (int16_t)a14;
    *(int16_t *)(v5 + 0x3a10) = (int16_t)a15;
    *(char *)(v5 + 0x3e54) = (char)a16;
    *(int32_t *)(v5 + 0x3a14) = a17;
    *(char *)(v5 + 0x3a18) = (char)a18;
    *(char *)(v5 + 0x3e55) = (char)a19;
    *(int16_t *)(v5 + 0x3a1a) = (int16_t)a20;
    *(int32_t *)(v5 + 0x3a1c) = a21;
    *(int16_t *)(v5 + 0x3a20) = (int16_t)a22;
    *(int32_t *)(v5 + 0x3a24) = a23;
    *(int32_t *)(v5 + 0x3a28) = a24;
    return 0;
}

// Address range: 0x80497fd - 0x804a4e8
int32_t func_1(void) {
    // 0x80497fd
    int32_t v1; // 0x80497fd
    __x86_get_pc_thunk_ax(v1);
    int16_t v2 = 0; // 0x8049a8f
    char v3 = 113; // 0x80497fd
    int16_t v4 = -0x225d;
    char v5 = v3; // 0x804998c
    int16_t v6; // 0x80497fd
    for (int16_t i = 0; i < 21; i++) {
        // 0x8049978
        v6 = v4;
        v5--;
        v4 = v5 != 0 ? v6 : v6 & 43;
    }
    // 0x8049a8f
    v2++;
    v3 -= 21;
    while (v2 != 34) {
        v5 = v3;
        for (int16_t i = 0; i < 21; i++) {
            // 0x8049978
            v6 = v4;
            v5--;
            v4 = v5 != 0 ? v6 : v6 & 43;
        }
        // 0x8049a8f
        v2++;
        v3 -= 21;
    }
    // 0x804a3df
    set_var(8, -0x56d5, -8, 0, (int32_t)v4, 1, -1, -0x5c1c, 4, -87, -0x1a42, -0x4e5a5dfc, -44, 0x3d1a, 0xffff, 0, 2, 57, 0, 3, 1, 0x2d19, -0x30890dd4, -3);
    return 0;
}

// Address range: 0x804a4e8 - 0x804a846
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804a511
    int32_t v3; // 0x804a4e8
    if (v1 == (char **)2) {
        // 0x804a513
        int32_t v4; // 0x804a4e8
        int32_t str = *(int32_t *)(v4 + 4); // 0x804a519
        v2 = strcmp((char *)str, (char *)(v3 + 1065)) == 0;
    }
    // 0x804a539
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x2b25), v3 + 1067, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b29), v3 + 1072, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b2b), v3 + 1077, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b2d), v3 + 1082, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b31), v3 + 1087, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f85), v3 + 1092, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b33), v3 + 1097, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b35), v3 + 1102, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b37), v3 + 1108, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b38), v3 + 1114, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b39), v3 + 1120, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b3d), v3 + 1126, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b41), v3 + 1132, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b43), v3 + 1138, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b45), v3 + 1144, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f89), v3 + 1150, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b49), v3 + 1156, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2b4d), v3 + 1162, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f8a), v3 + 1168, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b4f), v3 + 1174, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b51), v3 + 1180, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2b55), v3 + 1186, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b59), v3 + 1192, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2b5d), v3 + 1198, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2b21), v2);
    return 0;
}

// Address range: 0x804a846 - 0x804a84a
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a846
    return result;
}

// Address range: 0x804a84a - 0x804a84e
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804a84a
    int32_t result; // 0x804a84a
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
