//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x2e5e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x1d5d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x80497ef
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2; // 0x8049626
    int32_t v3; // 0x8049626
    int32_t v4; // 0x8049626
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049626
    *(int32_t *)(v5 + 0x49f0) = a1;
    *(int16_t *)(v5 + 0x49f4) = (int16_t)a2;
    *(int16_t *)(v5 + 0x49f6) = (int16_t)a3;
    *(int16_t *)(v5 + 0x49f8) = (int16_t)a4;
    *(char *)(v5 + 0x4e70) = (char)a5;
    *(char *)(v5 + 0x49fa) = (char)a6;
    *(int16_t *)(v5 + 0x49fc) = (int16_t)a7;
    *(int32_t *)(v5 + 0x4a00) = a8;
    *(int32_t *)(v5 + 0x4a04) = a9;
    *(char *)(v5 + 0x4a08) = (char)a10;
    *(int32_t *)(v5 + 0x4a0c) = a11;
    *(int32_t *)(v5 + 0x4a10) = a12;
    *(int32_t *)(v5 + 0x4a14) = a13;
    *(int32_t *)(v5 + 0x4a18) = a14;
    *(int32_t *)(v5 + 0x4a1c) = a15;
    *(char *)(v5 + 0x4a20) = (char)a16;
    *(char *)(v5 + 0x4a21) = (char)a17;
    *(int16_t *)(v5 + 0x4a22) = (int16_t)a18;
    *(int16_t *)(v5 + 0x4a24) = (int16_t)a19;
    *(int32_t *)(v5 + 0x4a28) = a20;
    *(int32_t *)(v5 + 0x4a2c) = a21;
    *(int16_t *)(v5 + 0x4a30) = (int16_t)a22;
    *(char *)(v5 + 0x4a32) = (char)a23;
    *(int32_t *)(v5 + 0x4a34) = a24;
    *(int32_t *)(v5 + 0x4a38) = a25;
    *(char *)(v5 + 0x4a3c) = (char)a26;
    return 0;
}

// Address range: 0x80497ef - 0x804ae6c
int32_t func_1(void) {
    // 0x804ae64
    int32_t v1; // 0x80497ef
    __x86_get_pc_thunk_ax(v1);
    set_var(-0x2492fc8c, 0x59bb, 0x413f, 1, 0, 1, 1, -1, 0x7def5a7f, 9, 0x3ad813d1, 1, -0x5ab8e3bc, -1, -0x511d2796, 3, 229, 0x5745, 0x4bdb, -0x7769a89c, 3, 0xc918, 1, 0x4322c4ea, 1, -110);
    return 3;
}

// Address range: 0x804ae6c - 0x804b242
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804ae95
    int32_t v3; // 0x804ae6c
    if (v1 == (char **)2) {
        // 0x804ae97
        int32_t v4; // 0x804ae6c
        int32_t str = *(int32_t *)(v4 + 4); // 0x804ae9d
        v2 = strcmp((char *)str, (char *)(v3 + 1197)) == 0;
    }
    // 0x804aebd
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x31a1), v3 + 1199, v2);
    transparent_crc(-0x57325d52, v3 + 1203, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31a5), v3 + 1207, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31a7), v3 + 1212, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31a9), v3 + 1217, v2);
    transparent_crc(5, v3 + 1222, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3621), v3 + 1227, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31ab), v3 + 1232, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31ad), v3 + 1237, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31b1), v3 + 1242, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31b5), v3 + 1247, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31b9), v3 + 1253, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31bd), v3 + 1259, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31c1), v3 + 1265, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31c5), v3 + 1271, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31c9), v3 + 1277, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31cd), v3 + 1283, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31d1), v3 + 1289, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31d2), v3 + 1295, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31d3), v3 + 1301, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31d5), v3 + 1307, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31d9), v3 + 1313, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31dd), v3 + 1319, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x31e1), v3 + 1325, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31e3), v3 + 1331, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31e5), v3 + 1337, v2);
    transparent_crc(*(int32_t *)(v3 + 0x31e9), v3 + 1343, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x31ed), v3 + 1349, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x319d), v2);
    return 0;
}

// Address range: 0x804b242 - 0x804b246
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804b242
    return result;
}

// Address range: 0x804b246 - 0x804b24a
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804b246
    int32_t result; // 0x804b246
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
