//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x6ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x3d3e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x5c4a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x5b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x5b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x5bd9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x5b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x2c3d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049626 - 0x8049805
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32) {
    // 0x8049626
    int32_t v1; // 0x8049626
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804962f
    *(int32_t *)(v2 + 0x59f0) = a1;
    *(int32_t *)(v2 + 0x59f4) = a2;
    *(int32_t *)(v2 + 0x59f8) = a3;
    *(int32_t *)(v2 + 0x5e90) = a4;
    *(char *)(v2 + 0x5e94) = (char)a5;
    *(int32_t *)(v2 + 0x59fc) = a6;
    *(char *)(v2 + 0x5a00) = (char)a7;
    *(int16_t *)(v2 + 0x5a02) = (int16_t)a8;
    *(int16_t *)(v2 + 0x5a04) = (int16_t)a9;
    *(int32_t *)(v2 + 0x5a08) = a10;
    *(int16_t *)(v2 + 0x5a0c) = (int16_t)a11;
    *(int32_t *)(v2 + 0x5a10) = a12;
    *(char *)(v2 + 0x5a14) = (char)a13;
    *(int16_t *)(v2 + 0x5a16) = (int16_t)a14;
    *(int32_t *)(v2 + 0x5a18) = a15;
    *(char *)(v2 + 0x5a1c) = (char)a16;
    *(int32_t *)(v2 + 0x5a20) = a17;
    *(int32_t *)(v2 + 0x5a24) = a18;
    *(int32_t *)(v2 + 0x5a28) = a19;
    *(int32_t *)(v2 + 0x5a2c) = a20;
    *(int32_t *)(v2 + 0x5a30) = a21;
    *(char *)(v2 + 0x5a34) = (char)a22;
    *(int32_t *)(v2 + 0x5a38) = a23;
    *(int32_t *)(v2 + 0x5a3c) = a24;
    *(int32_t *)(v2 + 0x5a40) = a25;
    *(int32_t *)(v2 + 0x5a44) = a26;
    *(int16_t *)(v2 + 0x5e96) = (int16_t)a27;
    *(int32_t *)(v2 + 0x5a48) = a28;
    *(int32_t *)(v2 + 0x5a4c) = a29;
    *(int16_t *)(v2 + 0x5a50) = (int16_t)a30;
    *(char *)(v2 + 0x5e98) = (char)a31;
    *(int32_t *)(v2 + 0x5a54) = a32;
    return 0;
}

// Address range: 0x8049805 - 0x804bcc1
int32_t func_1(void) {
    // 0x8049805
    int32_t v1; // 0x8049805
    __x86_get_pc_thunk_ax(v1);
    while (true) {
        // continue -> 0x8049a25
    }
}

// Address range: 0x804bcc1 - 0x804c124
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804bcea
    int32_t v3; // 0x804bcc1
    if (v1 == (char **)2) {
        // 0x804bcec
        int32_t v4; // 0x804bcc1
        int32_t str = *(int32_t *)(v4 + 4); // 0x804bcf2
        v2 = strcmp((char *)str, (char *)(v3 + 1332)) == 0;
    }
    // 0x804bd12
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x334c), v3 + 1334, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3350), v3 + 1338, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3354), v3 + 1342, v2);
    transparent_crc(*(int32_t *)(v3 + 0x37ec), v3 + 1347, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x37f0), v3 + 1352, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3358), v3 + 1357, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x335c), v3 + 1362, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x335e), v3 + 1367, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3360), v3 + 1372, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3364), v3 + 1377, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3368), v3 + 1382, v2);
    transparent_crc(*(int32_t *)(v3 + 0x336c), v3 + 1388, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3370), v3 + 1394, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3372), v3 + 1400, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3374), v3 + 1406, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3378), v3 + 1412, v2);
    transparent_crc(1, v3 + 1418, v2);
    transparent_crc(*(int32_t *)(v3 + 0x337c), v3 + 1424, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3380), v3 + 1430, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3384), v3 + 1436, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3388), v3 + 1442, v2);
    transparent_crc(*(int32_t *)(v3 + 0x338c), v3 + 1448, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3390), v3 + 1454, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3394), v3 + 1460, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3398), v3 + 1466, v2);
    transparent_crc(*(int32_t *)(v3 + 0x339c), v3 + 1472, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33a0), v3 + 1478, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x37f2), v3 + 1484, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33a4), v3 + 1490, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33a8), v3 + 1496, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x33ac), v3 + 1502, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x37f4), v3 + 1508, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33b0), v3 + 1514, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x3348), v2);
    return 0;
}

// Address range: 0x804c124 - 0x804c128
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804c124
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
