//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x3ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x193e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x2c0a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x2b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x2b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x2b99 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x2b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 2109));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049654 - 0x8049760
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14) {
    // 0x8049654
    int32_t v1; // 0x8049654
    int32_t v2; // 0x8049654
    int32_t v3; // 0x8049654
    int32_t v4; // 0x8049654
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049654
    *(int16_t *)(v5 + 0x29c2) = (int16_t)a1;
    *(int16_t *)(v5 + 0x29c4) = (int16_t)a2;
    *(int16_t *)(v5 + 0x29c6) = (int16_t)a3;
    *(char *)(v5 + 0x2e22) = (char)a4;
    *(char *)(v5 + 0x29c8) = (char)a5;
    *(int32_t *)(v5 + 0x29ca) = a6;
    *(int32_t *)(v5 + 0x29ce) = a7;
    *(int32_t *)(v5 + 0x2e26) = a8;
    *(char *)(v5 + 0x29d2) = (char)a9;
    *(int16_t *)(v5 + 0x29d4) = (int16_t)a10;
    *(int32_t *)(v5 + 0x29d6) = a11;
    *(int16_t *)(v5 + 0x29da) = (int16_t)a12;
    *(int32_t *)(v5 + 0x29de) = a13;
    *(char *)(v5 + 0x29e2) = (char)a14;
    return 0;
}

// Address range: 0x8049760 - 0x8049ad8
int32_t func_1(void) {
    // 0x8049760
    int32_t v1; // 0x8049760
    __x86_get_pc_thunk_ax(v1);
    set_var(6, 0, 1, 0, -75, -10, -4, 0, -25, -6, 9, -0x1c72, -0x673c2cb2, 1);
    return 0x3372;
}

// Address range: 0x8049ad8 - 0x8049d23
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049b01
    int32_t v3; // 0x8049ad8
    if (v1 == (char **)2) {
        // 0x8049b03
        int32_t v4; // 0x8049ad8
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049b09
        v2 = strcmp((char *)str, (char *)(v3 + 801)) == 0;
    }
    // 0x8049b29
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2535), v3 + 803, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2537), v3 + 807, v2);
    transparent_crc(5, v3 + 811, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2539), v3 + 816, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2995), v3 + 821, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x253b), v3 + 826, v2);
    transparent_crc(*(int32_t *)(v3 + 0x253d), v3 + 831, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2541), v3 + 836, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2999), v3 + 841, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2545), v3 + 846, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2547), v3 + 851, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2549), v3 + 856, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x254d), v3 + 861, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2551), v3 + 866, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2555), v3 + 871, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2531), v2);
    return 0;
}

// Address range: 0x8049d23 - 0x8049d27
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x8049d23
    return result;
}

// Address range: 0x8049d27 - 0x8049d2b
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x8049d27
    int32_t result; // 0x8049d27
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
