//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x5ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x361e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x4c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x4b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x4b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x4bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x4b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 0x251d));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049654 - 0x80498ab
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24, int32_t a25, int32_t a26, int32_t a27, int32_t a28, int32_t a29, int32_t a30, int32_t a31, int32_t a32, int32_t a33) {
    // 0x8049654
    int32_t v1; // 0x8049654
    int32_t v2; // 0x8049654
    int32_t v3; // 0x8049654
    int32_t v4; // 0x8049654
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049654
    *(int32_t *)(v5 + 0x49c2) = a1;
    *(int32_t *)(v5 + 0x49c6) = a2;
    *(int32_t *)(v5 + 0x49ca) = a3;
    *(char *)(v5 + 0x49ce) = (char)a4;
    *(char *)(v5 + 0x4e42) = (char)a5;
    *(char *)(v5 + 0x49cf) = (char)a6;
    *(int32_t *)(v5 + 0x49d2) = a7;
    *(int32_t *)(v5 + 0x49d6) = a8;
    *(char *)(v5 + 0x49da) = (char)a9;
    *(int32_t *)(v5 + 0x49de) = a10;
    *(int16_t *)(v5 + 0x49e2) = (int16_t)a11;
    *(char *)(v5 + 0x49e4) = (char)a12;
    *(int32_t *)(v5 + 0x49e6) = a13;
    *(char *)(v5 + 0x49ea) = (char)a14;
    *(int32_t *)(v5 + 0x4e46) = a15;
    *(char *)(v5 + 0x49eb) = (char)a16;
    *(char *)(v5 + 0x49ec) = (char)a17;
    *(int16_t *)(v5 + 0x4e4a) = (int16_t)a18;
    *(int32_t *)(v5 + 0x49ee) = a19;
    *(char *)(v5 + 0x49f2) = (char)a20;
    *(int16_t *)(v5 + 0x49f4) = (int16_t)a21;
    *(int32_t *)(v5 + 0x4e4e) = a22;
    *(int32_t *)(v5 + 0x49f6) = a23;
    *(int32_t *)(v5 + 0x49fa) = a24;
    *(char *)(v5 + 0x49fe) = (char)a25;
    *(int32_t *)(v5 + 0x4a02) = a26;
    *(int16_t *)(v5 + 0x4a06) = (int16_t)a27;
    *(int32_t *)(v5 + 0x4a0a) = a28;
    *(char *)(v5 + 0x4a0e) = (char)a29;
    *(char *)(v5 + 0x4a0f) = (char)a30;
    *(int16_t *)(v5 + 0x4a10) = (int16_t)a31;
    *(char *)(v5 + 0x4a12) = (char)a32;
    *(int32_t *)(v5 + 0x4a16) = a33;
    return 0;
}

// Address range: 0x80498ab - 0x804b584
int32_t func_1(void) {
    // 0x8049f1f
    int32_t v1; // 0x80498ab
    __x86_get_pc_thunk_ax(v1);
    set_var(0, -1, 0x2324, 253, 0, 61, -4, -9, 220, -0x5a88236a, 0xffff, 247, 0, 114, 0, -56, 2, 0, 2, -10, 0xfff9, 0, -3, -5, 255, -4, 0xb6c5, -7, 19, 255, 0xd70e, 49, 1);
    return 86;
}

// Address range: 0x804b584 - 0x804ba00
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x804b5ad
    int32_t v3; // 0x804b584
    if (v1 == (char **)2) {
        // 0x804b5af
        int32_t v4; // 0x804b584
        int32_t str = *(int32_t *)(v4 + 4); // 0x804b5b5
        v2 = strcmp((char *)str, (char *)(v3 + 1361)) == 0;
    }
    // 0x804b5d5
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x2a89), v3 + 1363, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a8d), v3 + 1367, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a91), v3 + 1371, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a95), v3 + 1376, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2f09), v3 + 1381, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2a96), v3 + 1386, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a99), v3 + 1391, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2a9d), v3 + 1396, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2aa1), v3 + 1401, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2aa5), v3 + 1406, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2aa9), v3 + 1411, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2aab), v3 + 1416, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2aad), v3 + 1421, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ab1), v3 + 1427, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f0d), v3 + 1433, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ab2), v3 + 1439, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ab3), v3 + 1445, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2f11), v3 + 1451, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ab5), v3 + 1457, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ab9), v3 + 1463, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2abb), v3 + 1469, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2f15), v3 + 1475, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2abd), v3 + 1481, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ac1), v3 + 1487, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ac5), v3 + 1493, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ac9), v3 + 1499, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2acd), v3 + 1505, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2ad1), v3 + 1511, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ad5), v3 + 1517, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ad6), v3 + 1523, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x2ad7), v3 + 1529, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x2ad9), v3 + 1535, v2);
    transparent_crc(*(int32_t *)(v3 + 0x2add), v3 + 1541, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x2a85), v2);
    return 0;
}

// Address range: 0x804ba00 - 0x804ba04
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804ba00
    return result;
}

// Address range: 0x804ba04 - 0x804ba08
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804ba04
    int32_t result; // 0x804ba04
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
