//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x1d8e));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c0a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3b99 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 3213));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049654 - 0x8049736
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16) {
    // 0x8049654
    int32_t v1; // 0x8049654
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x804965d
    *(int32_t *)(v2 + 0x39c2) = a1;
    *(int32_t *)(v2 + 0x39c6) = a2;
    *(int32_t *)(v2 + 0x39ca) = a3;
    *(char *)(v2 + 0x39ce) = (char)a4;
    *(int16_t *)(v2 + 0x39d0) = (int16_t)a5;
    *(int32_t *)(v2 + 0x3e22) = a6;
    *(int32_t *)(v2 + 0x39d2) = a7;
    *(int32_t *)(v2 + 0x39d6) = a8;
    *(int32_t *)(v2 + 0x39da) = a9;
    *(int32_t *)(v2 + 0x39de) = a10;
    *(int32_t *)(v2 + 0x39e2) = a11;
    *(int32_t *)(v2 + 0x39e6) = a12;
    *(char *)(v2 + 0x39ea) = (char)a13;
    *(int16_t *)(v2 + 0x39ec) = (int16_t)a14;
    *(int16_t *)(v2 + 0x39ee) = (int16_t)a15;
    *(int32_t *)(v2 + 0x39f2) = a16;
    return 0;
}

// Address range: 0x8049736 - 0x8049f13
int32_t func_1(void) {
    // 0x8049736
    int32_t v1; // 0x8049736
    __x86_get_pc_thunk_ax(v1);
    while (true) {
        // continue -> 0x80497ef
    }
  lab_0x8049ec7:;
    // 0x8049ec7
    int32_t v2; // 0x8049736
    int32_t result = v2;
    uint32_t v3; // 0x8049736
    int32_t v4; // 0x8049736
    int16_t v5; // 0x8049736
    uint16_t v6; // 0x8049736
    int16_t v7; // 0x8049736
    int32_t v8; // 0x8049736
    int32_t v9; // 0x80497fc
    int32_t v10; // 0x8049805
    set_var(-0x2ee3, v9, 0x1000000 * v10 / 0x1000000, v3 % 256, 0x10000 * v8 / 0x10000, (int32_t)(v7 < 0), v4, result, -0x2686c775, 2, (int32_t)v5, 3, 5, (int32_t)v6, 0xfffa, -0x4a0e250e);
    return result;
}

// Address range: 0x8049f13 - 0x804a177
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049f3c
    int32_t v3; // 0x8049f13
    if (v1 == (char **)2) {
        // 0x8049f3e
        int32_t v4; // 0x8049f13
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049f44
        v2 = strcmp((char *)str, (char *)(v3 + 818)) == 0;
    }
    // 0x8049f64
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(*(int32_t *)(v3 + 0x30fa), v3 + 820, v2);
    transparent_crc(*(int32_t *)(v3 + 0x30fe), v3 + 824, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3102), v3 + 829, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3106), v3 + 834, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3108), v3 + 839, v2);
    transparent_crc(*(int32_t *)(v3 + 0x355a), v3 + 844, v2);
    transparent_crc(*(int32_t *)(v3 + 0x310a), v3 + 849, v2);
    transparent_crc(*(int32_t *)(v3 + 0x310e), v3 + 854, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3112), v3 + 859, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3116), v3 + 864, v2);
    transparent_crc(*(int32_t *)(v3 + 0x311a), v3 + 870, v2);
    transparent_crc(*(int32_t *)(v3 + 0x311e), v3 + 876, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3122), v3 + 882, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3124), v3 + 888, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3126), v3 + 894, v2);
    transparent_crc(*(int32_t *)(v3 + 0x312a), v3 + 900, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x30f6), v2);
    return 0;
}

// Address range: 0x804a177 - 0x804a17b
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x804a177
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 11
