//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t crc32_8bytes(uint32_t a1);
int32_t crc32_byte(int32_t a1);
int32_t crc32_gentab(void);
int32_t func_1(void);
int32_t platform_main_begin(void);
int32_t platform_main_end(int32_t a1, int32_t a2);
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24);
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x8048390 - 0x8048394
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x8048390
    int32_t result; // 0x8048390
    return result;
}

// Address range: 0x8048456 - 0x8048466
int32_t platform_main_begin(void) {
    // 0x8048456
    int32_t v1; // 0x8048456
    return __x86_get_pc_thunk_ax(v1) + 0x4ba2;
}

// Address range: 0x8048466 - 0x8048494
int32_t platform_main_end(int32_t a1, int32_t a2) {
    // 0x8048466
    int32_t v1; // 0x8048466
    return printf((char *)(__x86_get_pc_thunk_ax(v1) + 0x1bae));
}

// Address range: 0x804946b - 0x80494db
int32_t crc32_gentab(void) {
    // 0x804946b
    int32_t v1; // 0x804946b
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x8049471
    for (int32_t i = 0; i < 256; i++) {
        int32_t v3 = 8; // 0x80494b4
        uint32_t v4 = i / 2;
        int32_t v5 = i % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
        v3--;
        int32_t v6 = v5; // 0x80494bc
        while (v3 != 0) {
            // 0x804949a
            v4 = v6 / 2;
            v5 = v6 % 2 == 0 ? v4 : v4 ^ -0x12477ce0;
            v3--;
            v6 = v5;
        }
        // 0x80494be
        *(int32_t *)(v2 + 0x3c2a + 4 * i) = v5;
    }
    // 0x80494d8
    return v2 + 0x3b8a;
}

// Address range: 0x80494db - 0x8049522
int32_t crc32_byte(int32_t a1) {
    // 0x80494db
    int32_t v1; // 0x80494db
    int32_t v2 = __x86_get_pc_thunk_ax(v1); // 0x80494e2
    int32_t * v3 = (int32_t *)(v2 + 0x3b39); // 0x80494f2
    uint32_t v4 = *v3; // 0x80494f2
    *v3 = *(int32_t *)(v2 + 0x3bb9 + (4 * (v4 ^ a1) & 1020)) ^ v4 / 256;
    return v2 + 0x3b19;
}

// Address range: 0x8049522 - 0x8049577
int32_t crc32_8bytes(uint32_t a1) {
    // 0x8049522
    int32_t v1; // 0x8049522
    __x86_get_pc_thunk_ax(v1);
    crc32_byte(a1 % 256);
    crc32_byte(a1 / 256 % 256);
    crc32_byte(a1 / 0x10000 % 256);
    return crc32_byte(a1 / 0x1000000);
}

// Address range: 0x8049577 - 0x80495be
int32_t transparent_crc(int32_t a1, int32_t a2, int32_t a3) {
    // 0x8049577
    int32_t v1; // 0x8049577
    __x86_get_pc_thunk_bx(v1);
    int32_t chars_printed = crc32_8bytes(a1); // 0x8049598
    if (a3 != 0) {
        // 0x804959a
        chars_printed = printf((char *)(v1 + 2733));
    }
    // 0x80495b8
    return chars_printed;
}

// Address range: 0x8049654 - 0x80497f8
int32_t set_var(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24) {
    // 0x8049654
    int32_t v1; // 0x8049654
    int32_t v2; // 0x8049654
    int32_t v3; // 0x8049654
    int32_t v4; // 0x8049654
    __x86_get_pc_thunk_dx(v4, v2, v1, v3);
    int32_t v5; // 0x8049654
    *(int16_t *)(v5 + 0x39c2) = (int16_t)a1;
    *(int32_t *)(v5 + 0x39c6) = a2;
    *(int32_t *)(v5 + 0x39ca) = a3;
    *(int16_t *)(v5 + 0x39ce) = (int16_t)a4;
    *(int32_t *)(v5 + 0x39d2) = a5;
    *(int32_t *)(v5 + 0x39d6) = a6;
    *(int32_t *)(v5 + 0x39da) = a7;
    *(char *)(v5 + 0x39de) = (char)a8;
    *(int16_t *)(v5 + 0x39e0) = (int16_t)a9;
    *(char *)(v5 + 0x39e2) = (char)a10;
    *(int16_t *)(v5 + 0x39e4) = (int16_t)a11;
    *(int32_t *)(v5 + 0x39e6) = a12;
    *(char *)(v5 + 0x3e42) = (char)a13;
    *(int32_t *)(v5 + 0x39ea) = a14;
    *(int32_t *)(v5 + 0x39ee) = a15;
    *(int32_t *)(v5 + 0x39f2) = a16;
    *(int16_t *)(v5 + 0x39f6) = (int16_t)a17;
    *(char *)(v5 + 0x39f8) = (char)a18;
    *(int32_t *)(v5 + 0x3e46) = a19;
    *(int16_t *)(v5 + 0x39fa) = (int16_t)a20;
    *(int16_t *)(v5 + 0x39fc) = (int16_t)a21;
    *(int16_t *)(v5 + 0x3e4a) = (int16_t)a22;
    *(char *)(v5 + 0x39fe) = (char)a23;
    *(int32_t *)(v5 + 0x3a02) = a24;
    return 0;
}

// Address range: 0x80497f8 - 0x8049c2d
int32_t func_1(void) {
    // 0x8049ad7
    int32_t v1; // 0x80497f8
    __x86_get_pc_thunk_ax(v1);
    set_var(0, -0x3a7a, -1, 0xfffb, 7, -0x82e2bf0, -0x32e68f72, 64, 0, 102, 0x89d3, 2, 0, -1, -0x30c8, 1, 0x3379, 1, -0x30c8, 0x4189, 0x1f69, 0, 100, -8);
    return 1;
}

// Address range: 0x8049c2d - 0x8049f89
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = 0; // 0x8049c56
    int32_t v3; // 0x8049c2d
    if (v1 == (char **)2) {
        // 0x8049c58
        int32_t v4; // 0x8049c2d
        int32_t str = *(int32_t *)(v4 + 4); // 0x8049c5e
        v2 = strcmp((char *)str, (char *)(v3 + 1080)) == 0;
    }
    // 0x8049c7e
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x33e0), v3 + 1082, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33e4), v3 + 1086, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33e8), v3 + 1091, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x33ec), v3 + 1096, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33f0), v3 + 1101, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33f4), v3 + 1106, v2);
    transparent_crc(*(int32_t *)(v3 + 0x33f8), v3 + 1111, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x33fc), v3 + 1116, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x33fe), v3 + 1121, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3400), v3 + 1126, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3402), v3 + 1131, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3404), v3 + 1137, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3860), v3 + 1143, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3408), v3 + 1149, v2);
    transparent_crc(*(int32_t *)(v3 + 0x340c), v3 + 1155, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3410), v3 + 1161, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3414), v3 + 1167, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x3416), v3 + 1173, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3864), v3 + 1179, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3418), v3 + 1185, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x341a), v3 + 1191, v2);
    transparent_crc((int32_t)*(int16_t *)(v3 + 0x3868), v3 + 1197, v2);
    transparent_crc((int32_t)*(char *)(v3 + 0x341c), v3 + 1203, v2);
    transparent_crc(*(int32_t *)(v3 + 0x3420), v3 + 1209, v2);
    platform_main_end(-1 - *(int32_t *)(v3 + 0x33dc), v2);
    return 0;
}

// Address range: 0x8049f89 - 0x8049f8d
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x8049f89
    return result;
}

// Address range: 0x8049f8d - 0x8049f91
int32_t __x86_get_pc_thunk_dx(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x8049f8d
    int32_t result; // 0x8049f8d
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 12
